ALTER DATABASE db
    SET AUTOMATIC_TUNING = INHERIT;

ALTER DATABASE db
    SET AUTOMATIC_TUNING = CUSTOM;

ALTER DATABASE db
    SET AUTOMATIC_TUNING = AUTO;

ALTER DATABASE db
    SET AUTOMATIC_TUNING (CREATE_INDEX = ON);

ALTER DATABASE db
    SET AUTOMATIC_TUNING (CREATE_INDEX = OFF);

ALTER DATABASE db
    SET AUTOMATIC_TUNING (CREATE_INDEX = DEFAULT);

ALTER DATABASE db
    SET AUTOMATIC_TUNING (DROP_INDEX = ON);

ALTER DATABASE db
    SET AUTOMATIC_TUNING (DROP_INDEX = OFF);

ALTER DATABASE db
    SET AUTOMATIC_TUNING (DROP_INDEX = DEFAULT);

ALTER DATABASE db
    SET AUTOMATIC_TUNING (FORCE_LAST_GOOD_PLAN = ON);

ALTER DATABASE db
    SET AUTOMATIC_TUNING (FORCE_LAST_GOOD_PLAN = OFF);

ALTER DATABASE db
    SET AUTOMATIC_TUNING (FORCE_LAST_GOOD_PLAN = DEFAULT);

ALTER DATABASE db
    SET AUTOMATIC_TUNING (MAINTAIN_INDEX = ON);

ALTER DATABASE db
    SET AUTOMATIC_TUNING (MAINTAIN_INDEX = OFF);

ALTER DATABASE db
    SET AUTOMATIC_TUNING (MAINTAIN_INDEX = DEFAULT);

ALTER DATABASE db
    SET AUTOMATIC_TUNING (FORCE_LAST_GOOD_PLAN = ON, CREATE_INDEX = DEFAULT, MAINTAIN_INDEX = ON, DROP_INDEX = ON);

ALTER DATABASE db
    SET AUTOMATIC_TUNING = AUTO;

ALTER DATABASE db
    SET AUTOMATIC_TUNING (FORCE_LAST_GOOD_PLAN = OFF);


ALTER DATABASE db
    SET QUERY_STORE (DESIRED_STATE = READ_ONLY, QUERY_CAPTURE_MODE = ALL, SIZE_BASED_CLEANUP_MODE = OFF, INTERVAL_LENGTH_MINUTES = 100, MAX_STORAGE_SIZE_MB = 1000, MAX_PLANS_PER_QUERY = 200, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 367), WAIT_STATS_CAPTURE_MODE = ON);

ALTER DATABASE db
    SET QUERY_STORE = ON(DESIRED_STATE = READ_ONLY, QUERY_CAPTURE_MODE = ALL, SIZE_BASED_CLEANUP_MODE = OFF, INTERVAL_LENGTH_MINUTES = 100, MAX_STORAGE_SIZE_MB = 1000, MAX_PLANS_PER_QUERY = 200, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 367), WAIT_STATS_CAPTURE_MODE = OFF);