ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 1;

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = 0;

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = 1;

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = ON;

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = OFF;

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = ON;

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = OFF;

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = OFF;

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = ON;

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = ON;

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = OFF;

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = ON;

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;

ALTER DATABASE SCOPED CONFIGURATION SET NEW_OPTION = NEW_VALUE;

ALTER DATABASE SCOPED CONFIGURATION SET NEW_OPTION = NEW_VALUE;

ALTER DATABASE SCOPED CONFIGURATION SET NEW_OPTION = NEW_VALUE;

ALTER DATABASE SCOPED CONFIGURATION SET NEW_OPTION = 'quoted_value';

ALTER DATABASE SCOPED CONFIGURATION SET NEW_OPTION = ON;

ALTER DATABASE SCOPED CONFIGURATION SET NEW_OPTION = ON;

ALTER DATABASE SCOPED CONFIGURATION SET NEW_OPTION = OFF;

ALTER DATABASE SCOPED CONFIGURATION SET NEW_OPTION = 1;

ALTER DATABASE SCOPED CONFIGURATION SET NEW_OPTION = -10;

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET NEW_OPTION = PRIMARY;

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET NEW_OPTION = NEW_VALUE;

ALTER DATABASE SCOPED CONFIGURATION CLEAR PROCEDURE_CACHE;

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY CLEAR PROCEDURE_CACHE;