ALTER TABLE t1 ALTER COLUMN c1 ADD HIDDEN;

ALTER TABLE t1 ALTER COLUMN c1 DROP HIDDEN;

ALTER TABLE t1 ALTER COLUMN c1 INT HIDDEN NULL;

ALTER TABLE t1 ALTER COLUMN c1 INT HIDDEN NOT NULL;

ALTER TABLE t1 ALTER COLUMN c1 VARCHAR (MAX) HIDDEN NOT NULL;

ALTER TABLE t1 ALTER COLUMN c1 VARCHAR (100) COLLATE Traditional_Spanish_ci_ai HIDDEN NULL;

ALTER TABLE t1 ALTER COLUMN c1 INT SPARSE HIDDEN NULL;

ALTER TABLE t1 ALTER COLUMN c1 VARCHAR (100) COLLATE Traditional_Spanish_ci_ai SPARSE HIDDEN NULL;

ALTER TABLE t1 ALTER COLUMN c1 VARBINARY (MAX) COLLATE Traditional_Spanish_ci_ai FILESTREAM HIDDEN NULL;

ALTER TABLE t1 ALTER COLUMN c1 VARBINARY (MAX) SPARSE FILESTREAM HIDDEN NOT NULL;

ALTER TABLE t1 ALTER COLUMN c1 VARBINARY (MAX) SPARSE FILESTREAM HIDDEN NOT NULL;

ALTER TABLE t1 ALTER COLUMN c1 XML COLUMN_SET FOR ALL_SPARSE_COLUMNS HIDDEN NULL;

ALTER TABLE t1 ALTER COLUMN c1 NVARCHAR (60) COLLATE Latin1_General_BIN2  ENCRYPTED WITH (
     COLUMN_ENCRYPTION_KEY = key1,
     ENCRYPTION_TYPE = RANDOMIZED,
     ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256'
    ) HIDDEN;

ALTER TABLE t1 ALTER COLUMN c1 NVARCHAR (32) MASKED WITH (FUNCTION = 'default()') HIDDEN NOT NULL;