BULK INSERT t1 FROM 'f1'
    WITH (FORMAT = 'CSV');

BULK INSERT t1 FROM 'f1'
    WITH (FORMAT = 'CSV', FORMATFILE = 'ff1');

BULK INSERT t1 FROM 'f1'
    WITH (FORMAT = 'CSV', FIELDTERMINATOR = '!', DATAFILETYPE = 'char');

BULK INSERT t1 FROM 'f1'
    WITH (FORMAT = 'CSV', CODEPAGE = 'OEM', KEEPIDENTITY, KILOBYTES_PER_BATCH = 2, LASTROW = 10);

BULK INSERT t1 FROM 'f1'
    WITH (FORMAT = 'CSV', FIRSTROW = 1, LASTROW = 10, MAXERRORS = 0, ROWS_PER_BATCH = 1, ORDER (c1 ASC, c2 DESC));

BULK INSERT t1 FROM 'f1'
    WITH (FORMAT = 'CSV', FIELDQUOTE = '"');

BULK INSERT t1 FROM 'f1'
    WITH (FORMAT = 'CSV', FIELDQUOTE = '"', CODEPAGE = 'RAW');

BULK INSERT t1 FROM 'f1'
    WITH (FORMAT = 'CSV', FIELDQUOTE = '"', FORMATFILE = 'ff1', ORDER (c1), ERRORFILE = 'ef1');

BULK INSERT t1 FROM 'f1'
    WITH (FORMAT = 'CSV', FIELDQUOTE = '"', FIELDTERMINATOR = ',', ROWTERMINATOR = '\r\n', DATAFILETYPE = 'widechar');

BULK INSERT t1 FROM 'f1'
    WITH (FORMAT = 'CSV', FIELDQUOTE = '"', FIRSTROW = 5, LASTROW = 10, MAXERRORS = 0, ROWS_PER_BATCH = 1, FIRE_TRIGGERS, KEEPNULLS);

BULK INSERT t1 FROM 'f1'
    WITH (FORMAT = 'csv');

BULK INSERT t1 FROM 'f1'
    WITH (DATAFILETYPE = 'char', FIELDQUOTE = '"', FORMAT = 'cSv');

