SELECT *
FROM OPENROWSET (BULK 'f1', FORMATFILE = 'ff1', FORMAT = 'CSV') AS a;

SELECT *
FROM OPENROWSET (BULK 'f1', FORMATFILE = 'ff1', FORMAT = 'CSV', CODEPAGE = 'OEM', ROWS_PER_BATCH = 2, LASTROW = 10) AS a;

SELECT *
FROM OPENROWSET (BULK 'f1', FORMATFILE = 'ff1', FORMAT = 'CSV', FIRSTROW = 1, LASTROW = 10, MAXERRORS = 0, ROWS_PER_BATCH = 1, ORDER (c1 ASC, c2 DESC)) AS a;

SELECT *
FROM OPENROWSET (BULK 'f1', FORMATFILE = 'ff1', FORMAT = 'CSV', FIELDQUOTE = '"') AS a;

SELECT *
FROM OPENROWSET (BULK 'f1', FORMATFILE = 'ff1', FORMAT = 'CSV', FIELDQUOTE = '"', CODEPAGE = 'RAW') AS a;

SELECT *
FROM OPENROWSET (BULK 'f1', FORMATFILE = 'ff1', FORMAT = 'CSV', FIELDQUOTE = '"', ORDER (c1), ERRORFILE = 'ef1') AS a;

SELECT *
FROM OPENROWSET (BULK 'f1', FORMATFILE = 'ff1', FORMAT = 'CSV', FIELDQUOTE = '"', FIRSTROW = 5, LASTROW = 10, MAXERRORS = 0, ROWS_PER_BATCH = 1) AS a;

SELECT *
FROM OPENROWSET (BULK 'f1', FORMATFILE = 'ff1', FORMAT = 'Csv') AS a;

SELECT *
FROM OPENROWSET (BULK 'f1', FIELDQUOTE = '"', FORMAT = 'csV', FORMATFILE = 'ff1') AS a;