//------------------------------------------------------------------------------
// <copyright file="DbccCommands.cs" company="Microsoft">
//         Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
//------------------------------------------------------------------------------


namespace Microsoft.SqlServer.TransactSql.ScriptDom
{
#pragma warning disable 1591

    /// <summary>
    /// The possible values for dbcc commands
    /// </summary>               
    public enum DbccCommand
    {
        None            = 0,
	    ActiveCursors   = 1,
	    AddExtendedProc = 2,
	    AddInstance     = 3,
	    AuditEvent      = 4,
	    AutoPilot       = 5,
	    Buffer          = 6,
	    Bytes           = 7,
	    CacheProfile    = 8,
	    CacheStats      = 9,
	    CallFullText    = 10,
	    CheckAlloc      = 11,
	    CheckCatalog    = 12,
	    CheckConstraints= 13,
	    CheckDB         = 14,		
	    CheckFileGroup  = 15,
	    CheckIdent      = 16,
	    CheckPrimaryFile= 17,
	    CheckTable      = 18,
	    CleanTable      = 19,
	    ClearSpaceCaches= 20,
	    CollectStats    = 21,
	    ConcurrencyViolation = 22,
	    CursorStats     = 23,
	    DBRecover       = 24,
	    DBReindex       = 25,
	    DBReindexAll    = 26,
	    DBRepair        = 27,
	    DebugBreak      = 28,
	    DeleteInstance  = 29,
	    DetachDB        = 30,
	    DropCleanBuffers= 31,
	    DropExtendedProc= 32,
	    DumpConfig      = 33,
	    DumpDBInfo      = 34,
	    DumpDBTable     = 35,
	    DumpLock        = 36,
	    DumpLog         = 37,
	    DumpPage        = 38,
	    DumpResource    = 39,
	    DumpTrigger     = 40,
	    ErrorLog        = 41,
	    ExtentInfo      = 42,
	    FileHeader      = 43,
	    FixAllocation   = 44,
	    Flush           = 45, 
	    FlushProcInDB   = 46,
	    ForceGhostCleanup=47,
	    Free			= 48,
	    FreeProcCache   = 49,
	    FreeSessionCache= 50,
	    FreeSystemCache = 51,
	    FreezeIO        = 52,
	    Help            = 53,
	    IcecapQuery     = 54,
	    IncrementInstance=55,
	    Ind             = 56,
	    IndexDefrag     = 57,
	    InputBuffer     = 58,
	    InvalidateTextptr=59,
	    InvalidateTextptrObjid = 60,
	    Latch           = 61,
	    LogInfo         = 62,
	    MapAllocUnit    = 63,
	    MemObjList      = 64,
	    MemoryMap       = 65,
	    MemoryStatus    = 66,
	    Metadata        = 67,
	    MovePage        = 68,
	    NoTextptr       = 69,	
	    OpenTran        = 70,
	    OptimizerWhatIf = 71,
	    OutputBuffer    = 72,
	    PerfMonStats    = 73,
	    PersistStackHash= 74,
	    PinTable        = 75,
	    ProcCache       = 76,
	    PrtiPage        = 77,
	    ReadPage        = 78,
	    RenameColumn    = 79,
	    RuleOff         = 80,
	    RuleOn          = 81,
	    SeMetadata      = 82,
	    SetCpuWeight    = 83,
	    SetInstance     = 84,
	    SetIOWeight     = 85,
	    ShowStatistics  = 86,
	    ShowContig      = 87,
	    ShowDBAffinity  = 88,
	    ShowFileStats   = 89,
	    ShowOffRules    = 90,
	    ShowOnRules     = 91,
	    ShowTableAffinity=92,
	    ShowText        = 93,
	    ShowWeights     = 94,
	    ShrinkDatabase  = 95,
	    ShrinkFile      = 96,
	    SqlMgrStats     = 97,
	    SqlPerf         = 98,
	    StackDump       = 99,
	    Tec             = 100,
	    ThawIO          = 101,
	    ThrottleIO      = 102,
	    TraceOff        = 103,
	    TraceOn         = 104,
	    TraceStatus     = 105,
	    UnpinTable      = 106,
	    UpdateUsage     = 107,
	    UsePlan         = 108,
	    UserOptions     = 109,
	    WritePage       = 110,
    }

#pragma warning restore 1591
}
