CREATE EXTERNAL FILE FORMAT eff1
    WITH (
    FORMAT_TYPE = DELTA
    );

CREATE EXTERNAL FILE FORMAT eff2
    WITH (
    FORMAT_TYPE = DELIMITEDTEXT,
    FORMAT_OPTIONS (PARSER_VERSION = '2.0')
    );