SELECT CONVERT (JSON, CONVERT (CHAR (300), '{}'));

SELECT CONVERT (JSON, CONVERT (NCHAR (300), '{}'));

SELECT CONVERT (JSON, CONVERT (VARCHAR (MAX), '{}'));

SELECT CONVERT (JSON, CONVERT (NVARCHAR (300), '{}'));

SELECT CONVERT (CHAR (300), CONVERT (JSON, '{}'));

SELECT CONVERT (NCHAR (300), CONVERT (JSON, '{}'));

SELECT CONVERT (VARCHAR (300), CONVERT (JSON, '{}'));

SELECT CONVERT (NVARCHAR (MAX), CONVERT (JSON, '{}'));

SELECT CAST (CAST ('{}' AS CHAR (300)) AS JSON);

SELECT CAST (CAST ('{}' AS NCHAR (300)) AS JSON);

SELECT CAST (CAST ('{}' AS VARCHAR (MAX)) AS JSON);

SELECT CAST (CAST ('{}' AS NVARCHAR (300)) AS JSON);

SELECT CAST (CAST ('{}' AS JSON) AS CHAR (300));

SELECT CAST (CAST ('{}' AS JSON) AS NCHAR (300));

SELECT CAST (CAST ('{}' AS JSON) AS VARCHAR (300));

SELECT CAST (CAST ('{}' AS JSON) AS NVARCHAR (MAX));