SELECT CONVERT (JSON, CONVERT (CHAR (300), '{}'));

SELECT CONVERT (JSON, CONVERT (NCHAR (300), '{}'));

SELECT CONVERT (JSON, CONVERT (VARCHAR (MAX), '{}'));

SELECT CONVERT (JSON, CONVERT (NVARCHAR (300), '{}'));

SELECT CONVERT (CHAR (300), CONVERT (JSON, '{}'));

SELECT CONVERT (NCHAR (300), CONVERT (JSON, '{}'));

SELECT CONVERT (VARCHAR (300), CONVERT (JSON, '{}'));

SELECT CONVERT (NVARCHAR (MAX), CONVERT (JSON, '{}'));

SELECT CAST (CAST ('{}' AS CHAR (300)) AS JSON);

SELECT CAST (CAST ('{}' AS NCHAR (300)) AS JSON);

SELECT CAST (CAST ('{}' AS VARCHAR (MAX)) AS JSON);

SELECT CAST (CAST ('{}' AS NVARCHAR (300)) AS JSON);

SELECT CAST (CAST ('{}' AS JSON) AS CHAR (300));

SELECT CAST (CAST ('{}' AS JSON) AS NCHAR (300));

SELECT CAST (CAST ('{}' AS JSON) AS VARCHAR (300));

SELECT CAST (CAST ('{}' AS JSON) AS NVARCHAR (MAX));

SELECT CONVERT (VECTOR (2), CONVERT (VARCHAR (MAX), '[1,1]'));

SELECT CONVERT (VECTOR (2), CONVERT (NVARCHAR (MAX), N'[1,1]'));

SELECT CONVERT (VECTOR (2), CONVERT (JSON, '[1,1]'));

SELECT CAST (CAST ('[1,1]' AS VARCHAR (MAX)) AS VECTOR (2));

SELECT CAST (CAST (N'[1,1]' AS NVARCHAR (MAX)) AS VECTOR (2));

SELECT CAST (CAST ('[1,1]' AS JSON) AS VECTOR (2));

SELECT CONVERT (VARCHAR (MAX), CONVERT (VECTOR (3), '[0.1, 0.2, 0.1]'));

SELECT CONVERT (NVARCHAR (MAX), CONVERT (VECTOR (3), '[0.1, 0.2, 0.1]'));

SELECT CONVERT (JSON, CONVERT (VECTOR (3), '[0.1, 0.2, 0.1]'));

SELECT CAST (CAST ('[0.1, 0.1, 0.1]' AS VECTOR (3)) AS VARCHAR (MAX));

SELECT CAST (CAST ('[0.1, 0.1, 0.1]' AS VECTOR (3)) AS NVARCHAR (MAX));

SELECT CAST (CAST ('[0.1, 0.1, 0.1]' AS VECTOR (3)) AS JSON);
