SELECT DeptId,
       APPROX_PERCENTILE_CONT(0.10) WITHIN GROUP (ORDER BY Salary) AS 'P10',
       APPROX_PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY Salary) AS 'P90'
FROM tblEmployee
GROUP BY DeptId;

SELECT DeptId,
       APPROX_PERCENTILE_DISC(0.10) WITHIN GROUP (ORDER BY Salary) AS 'P10',
       APPROX_PERCENTILE_DISC(0.90) WITHIN GROUP (ORDER BY Salary) AS 'P90'
FROM tblEmployee
GROUP BY DeptId;