CREATE FUNCTION dbo.MyExternalFn AS EXTERNAL FUNCTION mySet.myFn;

GO
ALTER FUNCTION dbo.MyExternalFn AS EXTERNAL FUNCTION mySet.anotherFn;

GO
CREATE OR ALTER FUNCTION dbo.MyExternalFn AS EXTERNAL FUNCTION mySet.myFn;

GO
CREATE FUNCTION MyFn AS EXTERNAL FUNCTION myFn;

GO
CREATE FUNCTION dbo.MyExternalFn RETURNS MONEY AS EXTERNAL FUNCTION mySet.myFn;

GO
ALTER FUNCTION dbo.MyExternalFn RETURNS NVARCHAR (100) AS EXTERNAL FUNCTION mySet.myFn;

GO
CREATE OR ALTER FUNCTION dbo.MyExternalFn RETURNS INT AS EXTERNAL FUNCTION mySet.myFn;

GO
CREATE FUNCTION dbo.MyExternalFn (@x INT) AS EXTERNAL FUNCTION mySet.myFn;

GO
CREATE FUNCTION dbo.MyExternalFn (@x INT, @y NVARCHAR (50)) RETURNS INT AS EXTERNAL FUNCTION mySet.myFn;

GO
ALTER FUNCTION dbo.MyExternalFn (@x INT) RETURNS BIGINT AS EXTERNAL FUNCTION mySet.myFn;

GO
CREATE OR ALTER FUNCTION dbo.MyExternalFn (@x INT) RETURNS INT AS EXTERNAL FUNCTION mySet.myFn;

GO
DROP FUNCTION dbo.MyExternalFn;

GO
SELECT dbo.MyExternalFn();

GO
SELECT dbo.MyExternalFn(42, N'hello');

GO
DECLARE @v AS INT = 1;

SELECT dbo.MyExternalFn(@v, 'const');

GO
SELECT dbo.MyExternalFn(t.col1, t.col2) AS r
FROM dbo.t AS t;
