ALTER DATABASE d1
    SET COMPATIBILITY_LEVEL = 90;

ALTER DATABASE d1
    SET COMPATIBILITY_LEVEL = 10;

ALTER DATABASE d1
    SET ENCRYPTION ON,
        ENCRYPTION OFF;

ALTER DATABASE d1
    SET HONOR_BROKER_PRIORITY ON,
        VARDECIMAL_STORAGE_FORMAT OFF;

ALTER DATABASE d1
    SET VARDECIMAL_STORAGE_FORMAT ON,
        HONOR_BROKER_PRIORITY OFF;

ALTER DATABASE d1
    SET CHANGE_TRACKING = OFF;

ALTER DATABASE d1
    SET CHANGE_TRACKING = ON;

ALTER DATABASE d1
    SET CHANGE_TRACKING = ON(AUTO_CLEANUP = ON);

ALTER DATABASE d1
    SET CHANGE_TRACKING (AUTO_CLEANUP = OFF, CHANGE_RETENTION = 100 HOURS);

ALTER DATABASE d1
    SET CHANGE_TRACKING (CHANGE_RETENTION = 3 DAYS);

ALTER DATABASE d1
    SET CHANGE_TRACKING (CHANGE_RETENTION = 5 MINUTES, AUTO_CLEANUP = OFF);