ALTER TABLE t1 REBUILD;

ALTER TABLE t1 REBUILD PARTITION = ALL;

ALTER TABLE t1 REBUILD PARTITION = 1 WITH (MAXDOP = 2);

ALTER TABLE t1 REBUILD WITH (SORT_IN_TEMPDB = ON, MAXDOP = 2);

ALTER TABLE t1 ENABLE CHANGE_TRACKING;

ALTER TABLE t1 DISABLE CHANGE_TRACKING;

ALTER TABLE t1 ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);

ALTER TABLE t1 ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF);

ALTER TABLE t1 SET (LOCK_ESCALATION = AUTO, LOCK_ESCALATION = TABLE);

ALTER TABLE t1 SET (FILESTREAM_ON = something, LOCK_ESCALATION = DISABLE);

ALTER TABLE t1 SET (FILESTREAM_ON = 'something_else');

ALTER TABLE t1 ALTER COLUMN c1 ADD SPARSE;

ALTER TABLE t1 ALTER COLUMN c1 DROP SPARSE;

ALTER TABLE t1 ALTER COLUMN c1 VARBINARY (MAX) SPARSE FILESTREAM NOT NULL;

ALTER TABLE t1 ALTER COLUMN c1 INT SPARSE;

ALTER TABLE t1 ALTER COLUMN c1 XML COLUMN_SET FOR ALL_SPARSE_COLUMNS NULL;

ALTER TABLE t1 ALTER COLUMN c1 NVARCHAR (10) COLLATE latin1_general_bin SPARSE;