CREATE ASYMMETRIC KEY k1
     FROM PROVIDER p1 WITH ALGORITHM = DES;

CREATE ASYMMETRIC KEY k1
     FROM PROVIDER p1 WITH ALGORITHM = RC2, PROVIDER_KEY_NAME = 'kn1', CREATION_DISPOSITION = CREATE_NEW;

CREATE ASYMMETRIC KEY k1
     FROM PROVIDER p1 WITH ALGORITHM = DES
    ENCRYPTION BY PASSWORD = 'PLACEHOLDER';


GO
DROP ASYMMETRIC KEY k1 REMOVE PROVIDER KEY;