CREATE TABLE t1 (
    c1 INT
)
WITH (DATA_COMPRESSION = NONE, DATA_COMPRESSION = ROW ON PARTITIONS (1));

CREATE TABLE t1 (
    c1 INT
)
WITH (DATA_COMPRESSION = PAGE ON PARTITIONS (2, 3 TO 5, 4));

CREATE TABLE t1 (
    c1 INT
) TEXTIMAGE_ON 'bbb' FILESTREAM_ON 'aaa'
WITH (DATA_COMPRESSION = NONE);


GO
CREATE TABLE t1 (
    c1 INT
) TEXTIMAGE_ON someGroup FILESTREAM_ON anotherGroup;


GO
CREATE TABLE t1 (
    c1 INT
) FILESTREAM_ON anotherGroup;