WITH CHANGE_TRACKING_CONTEXT (0xff), DirReps (c1, c2)
AS (SELECT c1
    FROM t1)
INSERT @v1
DEFAULT VALUES;


GO
WITH CHANGE_TRACKING_CONTEXT (0xff), DirReps (c1, c2)
AS (SELECT c1
    FROM t1)
UPDATE t1
SET c1 = 23 + 10;


GO
WITH CHANGE_TRACKING_CONTEXT (0xff), DirReps (c1, c2)
AS (SELECT c1
    FROM t1)
DELETE t1
FROM t1;


GO
WITH CHANGE_TRACKING_CONTEXT (0xff)
DELETE t1
FROM t1;