DROP INDEX i1
    ON t1
    WITH (ONLINE = ON, MOVE TO fg1, FILESTREAM_ON ab), i2
    ON t2
    WITH (ONLINE = OFF, MOVE TO fg1 (c1));

DROP INDEX i1
    ON t1
    WITH (ONLINE = ON, MOVE TO fg1, FILESTREAM_ON "ab"), i2
    ON t2
    WITH (ONLINE = OFF, MOVE TO fg1 (c1), DATA_COMPRESSION = PAGE);

DROP INDEX i1
    ON t1
    WITH (ONLINE = ON, MOVE TO fg1, DATA_COMPRESSION = ROW);

DROP INDEX i1
    ON t1
    WITH (DATA_COMPRESSION = ROW);

DROP INDEX i1
    ON t1
    WITH (MOVE TO fg1, FILESTREAM_ON ab);