CREATE PROCEDURE p1
AS
BEGIN
    INSERT INTO t1
    VALUES (1, 2),
    (DEFAULT, 0),
    (NULL, NULL);
    INSERT INTO t2
    VALUES ('aaa', 'bbb', 1),
    ('ccc', 'ddd', 20);
END


GO
CREATE PROCEDURE p1
AS
BEGIN
    INSERT INTO t2
    VALUES (1)
    OPTION (MAXDOP 2, KEEP PLAN);
    INSERT INTO t2
    DEFAULT VALUES
    OPTION (FAST 5, TABLE HINT(t2, READCOMMITTED, INDEX (i1)));
    INSERT INTO t2
    DEFAULT VALUES
    OPTION (TABLE HINT(t2));
END


GO
CREATE PROCEDURE p1
AS
BEGIN
    INSERT INTO t1 ($ACTION, $CUID, $ROWGUID)
    VALUES        (1, 2, 3);
END