UPDATE t2
SET $ROWGUID = newid();


GO
SELECT *
FROM t1
OPTION (OPTIMIZE FOR (@v1 = 20, @v2 = NULL), OPTIMIZE FOR (@v3 = 'zzz'), OPTIMIZE FOR (@v4 UNKNOWN));


GO
DBCC CHECKDB
    WITH ALL_ERRORMSGS, EXTENDED_LOGICAL_CHECKS;