CREATE SYMMETRIC KEY k1 FROM PROVIDER p1;

CREATE SYMMETRIC KEY k1 FROM PROVIDER p1
    WITH CREATION_DISPOSITION = CREATE_NEW;

CREATE SYMMETRIC KEY k1 FROM PROVIDER p1
    WITH PROVIDER_KEY_NAME = 'key1', ALGORITHM = RC4, CREATION_DISPOSITION = OPEN_EXISTING;

CREATE SYMMETRIC KEY k1 FROM PROVIDER p1
    ENCRYPTION BY CERTIFICATE c1;


GO
DROP SYMMETRIC KEY k1 REMOVE PROVIDER KEY;