-- Regression tests for GitHub issue #222: ALTER AVAILABILITY GROUP ... { GRANT | DENY } CREATE ANY DATABASE.
ALTER AVAILABILITY GROUP [SalesAG] GRANT CREATE ANY DATABASE
GO
ALTER AVAILABILITY GROUP [SalesAG] DENY CREATE ANY DATABASE
GO
