ALTER AVAILABILITY GROUP [SalesAG] ADD REPLICA ON 'node1' WITH (BACKUP_PRIORITY = 50);


GO
ALTER AVAILABILITY GROUP [SalesAG] ADD REPLICA ON 'node2' WITH (ENDPOINT_URL = 'TCP://node2:5022', FAILOVER_MODE = MANUAL, AVAILABILITY_MODE = ASYNCHRONOUS_COMMIT, BACKUP_PRIORITY = 50);


GO
ALTER AVAILABILITY GROUP [SalesAG] MODIFY REPLICA ON 'node1' WITH (BACKUP_PRIORITY = 100);
