CREATE TABLE t1 AS FILETABLE;


GO
CREATE TABLE t1 AS FILETABLE ON fg1 TEXTIMAGE_ON "default" FILESTREAM_ON "default"
WITH (FILETABLE_DIRECTORY = 'foo', FILETABLE_COLLATE_FILENAME = database_default);


GO
CREATE TABLE t1 AS FILETABLE
WITH (FILETABLE_COLLATE_FILENAME = Latin1_General_bin, FILETABLE_DIRECTORY = NULL);


GO
ALTER TABLE t1 ENABLE FILETABLE_NAMESPACE;


GO
ALTER TABLE t1 DISABLE FILETABLE_NAMESPACE;


GO
ALTER TABLE t1 SET (FILETABLE_DIRECTORY = 'foo');


GO
CREATE TABLE t AS FILETABLE
WITH (FILETABLE_PRIMARY_KEY_CONSTRAINT_NAME = foo);


GO
CREATE TABLE t AS FILETABLE
WITH (FILETABLE_STREAMID_UNIQUE_CONSTRAINT_NAME = foo);


GO
CREATE TABLE t AS FILETABLE
WITH (FILETABLE_FULLPATH_UNIQUE_CONSTRAINT_NAME = foo);


GO
CREATE TABLE t1 (
    c1 BIGINT PRIMARY KEY NOT NULL
) FEDERATED ON (c1 = c1);
