CREATE AVAILABILITY GROUP group1
WITH (REQUIRED_COPIES_TO_COMMIT = 10)
FOR DATABASE db1, db2
REPLICA ON 'server1' WITH (AVAILABILITY_MODE = SYNCHRONOUS_COMMIT, FAILOVER_MODE = AUTOMATIC, ENDPOINT_URL = 'TCP://1234:80', SECONDARY_ROLE (ALLOW_CONNECTIONS = NO), SESSION_TIMEOUT = 10, APPLY_DELAY = 1),
'server2' WITH (FAILOVER_MODE = MANUAL, APPLY_DELAY = 1, ENDPOINT_URL = 'TCP://1234:80', PRIMARY_ROLE (ALLOW_CONNECTIONS = READ_WRITE), AVAILABILITY_MODE = ASYNCHRONOUS_COMMIT, SESSION_TIMEOUT = 10),
'server3' WITH (AVAILABILITY_MODE = SYNCHRONOUS_COMMIT, FAILOVER_MODE = AUTOMATIC, ENDPOINT_URL = 'TCP://1234:80', SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL), SESSION_TIMEOUT = 10, APPLY_DELAY = 1);


GO
CREATE AVAILABILITY GROUP group1
WITH (REQUIRED_COPIES_TO_COMMIT = 10)
FOR DATABASE db1, db2
REPLICA ON 'server1' WITH (AVAILABILITY_MODE = SYNCHRONOUS_COMMIT, FAILOVER_MODE = AUTOMATIC, ENDPOINT_URL = 'TCP://1234:80', SECONDARY_ROLE (ALLOW_CONNECTIONS = READ_ONLY), SESSION_TIMEOUT = 10, APPLY_DELAY = 1),
'server2' WITH (FAILOVER_MODE = MANUAL, APPLY_DELAY = 1, ENDPOINT_URL = 'TCP://1234:80', PRIMARY_ROLE (ALLOW_CONNECTIONS = ALL), AVAILABILITY_MODE = ASYNCHRONOUS_COMMIT, SESSION_TIMEOUT = 10);