CREATE COLUMNSTORE INDEX cindx
    ON t(c1);

CREATE CLUSTERED COLUMNSTORE INDEX cindx
    ON t;

CREATE NONCLUSTERED COLUMNSTORE INDEX cindx
    ON t(c1, c2);

CREATE NONCLUSTERED COLUMNSTORE INDEX cindx
    ON t(c1, c2) WITH (DROP_EXISTING = ON);

CREATE NONCLUSTERED COLUMNSTORE INDEX cindx
    ON t(c1, c2) WITH (MAXDOP = 12);

CREATE NONCLUSTERED COLUMNSTORE INDEX cindx
    ON t(c1, c2) WITH (MAXDOP = 12, DROP_EXISTING = ON);

CREATE NONCLUSTERED COLUMNSTORE INDEX cindx
    ON t(c1, c2)
    ON ps (c1);

CREATE NONCLUSTERED COLUMNSTORE INDEX cindx
    ON t(c1, c2) WITH (MAXDOP = 12, DROP_EXISTING = ON)
    ON ps (c1);