ALTER DATABASE d1
    SET CONTAINMENT = NONE;

ALTER DATABASE d1
    SET CONTAINMENT = PARTIAL;

CREATE DATABASE d1 CONTAINMENT = NONE;

CREATE DATABASE d1
    WITH NESTED_TRIGGERS = ON;

CREATE DATABASE d1 CONTAINMENT = PARTIAL
    WITH NESTED_TRIGGERS = ON, TRUSTWORTHY ON, TRANSFORM_NOISE_WORDS = OFF, DEFAULT_LANGUAGE = [french], DEFAULT_FULLTEXT_LANGUAGE = 1033, TWO_DIGIT_YEAR_CUTOFF = 2000;

ALTER DATABASE CURRENT
    SET TRANSFORM_NOISE_WORDS = OFF,
        DEFAULT_LANGUAGE = 1033,
        DEFAULT_FULLTEXT_LANGUAGE = English,
        TWO_DIGIT_YEAR_CUTOFF = 2000,
        CONTAINMENT = PARTIAL,
        TRUSTWORTHY ON,
        COMPATIBILITY_LEVEL = 100,
        TRUSTWORTHY OFF;


GO
CREATE DATABASE d1
    ON 
    (NAME = file1, FILENAME = 'file1.mdf') FOR ATTACH
    WITH RESTRICTED_USER;

ALTER DATABASE d1
    SET HADR SUSPEND;


GO
ALTER DATABASE d1
    SET HADR RESUME;


GO
ALTER DATABASE d1
    SET HADR AVAILABILITY GROUP = g1;


GO
ALTER DATABASE d1
    SET HADR OFF;


GO
CREATE DATABASE d1
    WITH FILESTREAM(NON_TRANSACTED_ACCESS = OFF, DIRECTORY_NAME = NULL);

CREATE DATABASE d1
    WITH FILESTREAM(NON_TRANSACTED_ACCESS = READ_ONLY, DIRECTORY_NAME = 'dir1'), TRUSTWORTHY ON;

CREATE DATABASE d1
    WITH FILESTREAM(NON_TRANSACTED_ACCESS = FULL);


GO
CREATE DATABASE d1
    ON 
    (NAME = file1, FILENAME = 'file1.mdf') FOR ATTACH
    WITH FILESTREAM(DIRECTORY_NAME = 'dir1');


GO
ALTER DATABASE d1
    SET FILESTREAM(NON_TRANSACTED_ACCESS = OFF, DIRECTORY_NAME = NULL);


GO
ALTER DATABASE d1
    SET TARGET_RECOVERY_TIME = 42 SECONDS;


GO
ALTER DATABASE d1
    SET TARGET_RECOVERY_TIME = 42 MINUTES;


GO
CREATE DATABASE SCOPED CONTAINMENT = NONE;

CREATE DATABASE [SCOPED CREDENTIAL] CONTAINMENT = NONE;