SELECT  NEXT VALUE FOR seq1;

SELECT  NEXT VALUE FOR seq1,
        NEXT VALUE FOR sequence.seq1;

SELECT  NEXT VALUE FOR Sequence1 OVER (ORDER BY OrderDate DESC);

SELECT  NEXT VALUE FOR Sequence1 OVER (ORDER BY OrderDate DESC),
       IDENTITY (INT, 1, 1) AS ID_Num
FROM MyTable;

SELECT  NEXT VALUE FOR Sequence1 OVER (ORDER BY OrderDate DESC),
        NEXT VALUE FOR Sequence2 OVER (ORDER BY Customer ASC),
        NEXT VALUE FOR Sequence3,
       *
FROM MyTable;


GO
SELECT *
FROM t1
WHERE CONTAINS (PROPERTY(c1, 'my_property'), 'foo');


GO
SELECT TRY_CONVERT (INT, '12345');

SELECT TRY_CONVERT (DECIMAL (10, 5), TRY_CONVERT (VARBINARY (20), @myval));

SELECT TRY_CAST ('12345' AS INT);

SELECT TRY_CAST (@myval AS DECIMAL (10, 5));

SELECT IIF (3 > 4, 'A', 'B');

SELECT PARSE ('12345.54' AS FLOAT USING 'en-US');

SELECT PARSE ('12345.98' AS FLOAT);

SELECT TRY_PARSE ('12345.54' AS FLOAT USING 'en-US');

SELECT TRY_PARSE ('12345.98' AS FLOAT);