SELECT *
FROM T
ORDER BY a
OFFSET 5 ROWS FETCH NEXT 2 ROWS ONLY;

SELECT *
FROM T
ORDER BY a
OFFSET 5 ROWS FETCH NEXT 2 ROWS ONLY;

SELECT *
FROM T
ORDER BY a
OFFSET @p ROWS FETCH NEXT @r ROWS ONLY;

SELECT *
FROM T
ORDER BY a
OFFSET (SELECT count(*)
        FROM T2) ROWS FETCH NEXT (-1) ROWS ONLY;

SELECT *
FROM T
ORDER BY a
OFFSET 5 ROWS FETCH NEXT (SELECT count(*)
                          FROM T2) ROWS ONLY;

SELECT *
FROM T
ORDER BY a
OFFSET (5 + 2) ROWS FETCH NEXT 3 * 10 ROWS ONLY;

SELECT *
FROM T
ORDER BY a
OFFSET 5 ROWS FETCH NEXT (@p + 6) ROWS ONLY;

SELECT *
FROM T
ORDER BY a
OFFSET (sum(5)) ROWS FETCH NEXT 6 ROWS ONLY;

SELECT *
FROM t1 CROSS APPLY (SELECT *
                     FROM sys.objects
                     ORDER BY 1
                     OFFSET offset ROWS FETCH NEXT first ROWS ONLY) AS t1;

INSERT INTO t
SELECT *
FROM t
ORDER BY c1 ASC
OFFSET 1 ROWS FETCH NEXT 2 ROWS ONLY;