CREATE SERVER AUDIT a1 TO FILE (FILEPATH = 'aaa', MAX_FILES = 10) WITH (ON_FAILURE = FAIL_OPERATION)
    WHERE c1 = 1;


GO
ALTER SERVER AUDIT a1
    WHERE c1 = 1;


GO
ALTER SERVER AUDIT a1 REMOVE WHERE;


GO
ALTER SERVER AUDIT a1 TO FILE (FILEPATH = 'aaa', MAX_FILES = 10) WITH (ON_FAILURE = FAIL_OPERATION, QUEUE_DELAY = 2)
    WHERE c1 = 1;