CREATE INDEX ind1
    ON t1(c1);

CREATE UNIQUE INDEX ind1
    ON t1(c1 ASC);

CREATE UNIQUE CLUSTERED INDEX ind1
    ON t1(c1 ASC, c2, c3 DESC);

CREATE UNIQUE NONCLUSTERED INDEX ind1
    ON tempdb.dbo.t1(c1)
    WITH FILLFACTOR = 23, PAD_INDEX;

CREATE UNIQUE NONCLUSTERED INDEX ind1
    ON tempdb.dbo.t1(c1)
    WITH FILLFACTOR = 23, PAD_INDEX
    ON [default];


GO
CREATE UNIQUE NONCLUSTERED INDEX ind1
    ON tempdb.dbo.t1(c1)
    WITH PAD_INDEX, FILLFACTOR = 23, IGNORE_DUP_KEY, DROP_EXISTING, STATISTICS_NORECOMPUTE, SORT_IN_TEMPDB;

CREATE INDEX ind1
    ON t1(c1)
    ON myFileGroup;

CREATE INDEX ind1
    ON t1(c1)
    ON 'myFileGroup';