SET DISABLE_DEF_CNST_CHK ON;


GO
CREATE TRIGGER trig1
    ON t1
    FOR INSERT
    WITH APPEND
    AS BEGIN
           PRINT '1';
       END


GO
INSERT table1 WITH (FASTFIRSTROW, HOLDLOCK) (c2, c3)
(SELECT *
 FROM t1);

DELETE table1 WITH (FASTFIRSTROW, HOLDLOCK);

SELECT c1
FROM t1 AS table1 WITH (INDEX (0, 1, ind2), FASTFIRSTROW, HOLDLOCK, NOLOCK, PAGLOCK, READCOMMITTED, READPAST, READUNCOMMITTED, REPEATABLEREAD, ROWLOCK, SERIALIZABLE, TABLOCK, TABLOCKX, UPDLOCK, XLOCK, NOWAIT), t2 WITH (INDEX (ind1), FASTFIRSTROW);


GO
RAISERROR 25 'hello';

RAISERROR 25 N'hello';

RAISERROR 25 @var1;

RAISERROR -10 @var1;

RAISERROR @firstVar @var1;


GO
RESTORE DATABASE db1 FROM @var1
    WITH DBO_ONLY;


GO
BACKUP DATABASE d1
    TO DISK = 'd:'
    WITH MEDIANAME = 'someMedia', MEDIAPASSWORD = 'PLACEHOLDER1', MEDIADESCRIPTION = 'md1';

BACKUP DATABASE d1
    TO DISK = 'd:'
    WITH RETAINDAYS = 10, PASSWORD = @pwdVar, FORMAT;