GRANT ALTER ANY EXTERNAL MODEL TO datascientist;

GRANT ALTER ANY EXTERNAL MODEL TO PUBLIC
    WITH GRANT OPTION;

GRANT ALTER ANY EXTERNAL MODEL TO mlrole, adminrole
    AS dbo;

GRANT EXECUTE
    ON EXTERNAL MODEL::MyPredictionModel TO analyst;

GRANT EXECUTE
    ON EXTERNAL MODEL::schema1.ModelName TO user1, user2
    WITH GRANT OPTION;

GRANT CONTROL
    ON EXTERNAL MODEL::dbo.SalesModel TO mladmin
    AS dbo;

GRANT VIEW DEFINITION
    ON EXTERNAL MODEL::MySchema.MyModel TO PUBLIC;

DENY ALTER ANY EXTERNAL MODEL TO restricteduser;

DENY EXECUTE
    ON EXTERNAL MODEL::TestModel TO guest CASCADE;

DENY CONTROL
    ON EXTERNAL MODEL::test.model1 TO user1, user2 CASCADE
    AS admin;

REVOKE ALTER ANY EXTERNAL MODEL TO olduser;

REVOKE GRANT OPTION FOR EXECUTE
    ON EXTERNAL MODEL::MyModel TO tempuser CASCADE;

REVOKE CONTROL
    ON EXTERNAL MODEL::prod.RecommendationModel TO contractor
    AS manager;

REVOKE EXECUTE
    ON EXTERNAL MODEL::dbo.CustomerModel TO PUBLIC CASCADE;

ALTER AUTHORIZATION
    ON EXTERNAL MODEL::MyModel
    TO newowner;

ALTER AUTHORIZATION
    ON EXTERNAL MODEL::schema1.ModelName
    TO SCHEMA OWNER;

ALTER AUTHORIZATION
    ON EXTERNAL MODEL::test.experimentalmodel
    TO datateam;

GRANT EXECUTE, VIEW DEFINITION
    ON EXTERNAL MODEL::MultiPermModel TO analyst;

DENY EXECUTE, CONTROL
    ON EXTERNAL MODEL::RestrictedModel TO guest;

REVOKE EXECUTE, VIEW DEFINITION
    ON EXTERNAL MODEL::OldModel TO formeranalyst;

GRANT EXECUTE
    ON EXTERNAL MODEL::MyDatabase.MySchema.ModelWithSpaces TO testuser;

DENY ALTER ANY EXTERNAL MODEL TO userwithspaces;

REVOKE CONTROL
    ON EXTERNAL MODEL::QuotedModel TO QuotedUser; 