CREATE FUNCTION dbo.TrimTest
(@str NVARCHAR (MAX))
RETURNS NVARCHAR (MAX)
AS
BEGIN
    RETURN TRIM('x' FROM @str);
END


GO
CREATE FUNCTION dbo.TrimTestNchar
(@str NVARCHAR (MAX))
RETURNS NVARCHAR (MAX)
AS
BEGIN
    RETURN TRIM(NCHAR(12288) FROM @str);
END


GO
CREATE FUNCTION dbo.TrimTestLeading
(@str NVARCHAR (MAX))
RETURNS NVARCHAR (MAX)
AS
BEGIN
    RETURN TRIM( LEADING 'x' FROM @str);
END


GO
CREATE FUNCTION dbo.TrimTestTrailing
(@str NVARCHAR (MAX))
RETURNS NVARCHAR (MAX)
AS
BEGIN
    RETURN TRIM( TRAILING 'x' FROM @str);
END


GO
CREATE FUNCTION dbo.TrimTestBoth
(@str NVARCHAR (MAX))
RETURNS NVARCHAR (MAX)
AS
BEGIN
    RETURN TRIM( BOTH 'x' FROM @str);
END
