ALTER TABLE dbo.t1 ALTER COLUMN [my column] ADD ROWGUIDCOL;

ALTER TABLE [tempdb].dbo.[table 2] ALTER COLUMN c1 DROP ROWGUIDCOL;

ALTER TABLE t1 ALTER COLUMN c1 INT;

ALTER TABLE t1 ALTER COLUMN c1 VARCHAR (20) COLLATE SomeCollation;

ALTER TABLE t1 ALTER COLUMN c1 VARCHAR (20) COLLATE SomeCollation NULL;

ALTER TABLE t1 ALTER COLUMN c1 INT NULL;

ALTER TABLE t1 ALTER COLUMN c1 INT NOT NULL;

ALTER TABLE t1 ALTER COLUMN c1 ADD NOT FOR REPLICATION;

ALTER TABLE t1 ALTER COLUMN c1 DROP NOT FOR REPLICATION;

