ALTER DATABASE d1
    SET ONLINE,
        OFFLINE 
    WITH NO_WAIT;

ALTER DATABASE d1
    SET SINGLE_USER 
    WITH ROLLBACK AFTER 10 SECONDS;

ALTER DATABASE d1
    SET RESTRICTED_USER,
        MULTI_USER 
    WITH ROLLBACK AFTER 10 SECONDS;

ALTER DATABASE d1
    SET READ_ONLY 
    WITH ROLLBACK IMMEDIATE;

ALTER DATABASE d1
    SET READ_WRITE;

ALTER DATABASE d1
    SET CURSOR_CLOSE_ON_COMMIT ON;

ALTER DATABASE d1
    SET CURSOR_CLOSE_ON_COMMIT OFF,
        CURSOR_DEFAULT LOCAL;

ALTER DATABASE d1
    SET CURSOR_DEFAULT GLOBAL;

ALTER DATABASE d1
    SET AUTO_CLOSE ON,
        AUTO_CREATE_STATISTICS OFF,
        AUTO_SHRINK ON;

ALTER DATABASE d1
    SET AUTO_UPDATE_STATISTICS ON;

ALTER DATABASE d1
    SET ANSI_NULL_DEFAULT ON,
        ANSI_NULLS OFF,
        ANSI_PADDING ON;

ALTER DATABASE d1
    SET ANSI_WARNINGS OFF,
        ARITHABORT ON,
        CONCAT_NULL_YIELDS_NULL OFF;

ALTER DATABASE d1
    SET NUMERIC_ROUNDABORT ON,
        QUOTED_IDENTIFIER OFF,
        RECURSIVE_TRIGGERS ON;

ALTER DATABASE d1
    SET RECOVERY FULL,
        TORN_PAGE_DETECTION OFF;

ALTER DATABASE d1
    SET TORN_PAGE_DETECTION ON,
        RECOVERY BULK_LOGGED;

ALTER DATABASE d1
    SET RECOVERY SIMPLE;

