BEGIN TRANSACTION;

BEGIN TRANSACTION;

BEGIN TRANSACTION myTransaction;

BEGIN DISTRIBUTED TRANSACTION;

BEGIN DISTRIBUTED TRANSACTION myTransaction;

BEGIN TRANSACTION @tranVariable;

BEGIN TRANSACTION
    WITH MARK;

BEGIN TRANSACTION myTransaction
    WITH MARK;

BEGIN TRANSACTION @tranVariable
    WITH MARK N'some tran';

BEGIN TRANSACTION myTransaction
    WITH MARK 'ascii literal';

BEGIN TRANSACTION myTransaction
    WITH MARK @descVariable;

