BULK INSERT db1.dbo.t1 FROM 'dataFile';

BULK INSERT dbo.t1 FROM someFile;

BULK INSERT v1 FROM 11;

BULK INSERT t1 FROM 'f1'
    WITH (BATCHSIZE = 10, CHECK_CONSTRAINTS, CODEPAGE = 866, DATAFILETYPE = 'char');

BULK INSERT t1 FROM 'f1'
    WITH (CODEPAGE = 'ACP', DATAFILETYPE = 'native', FIELDTERMINATOR = ':');

BULK INSERT t1 FROM 'f1'
    WITH (CODEPAGE = 'OEM', DATAFILETYPE = 'widechar', FIRSTROW = 5);

BULK INSERT t1 FROM 'f1'
    WITH (CODEPAGE = 'RAW', DATAFILETYPE = 'widenative', FIRE_TRIGGERS, KEEPNULLS);

BULK INSERT t1 FROM 'f1'
    WITH (FORMATFILE = 'SomeFile', KEEPIDENTITY, KILOBYTES_PER_BATCH = 2, LASTROW = 10);

BULK INSERT t1 FROM 'f1'
    WITH (MAXERRORS = 0, ORDER (timestamp ASC, t1 DESC, t2), DATAFILETYPE = 'widechar_ansi');

BULK INSERT t1 FROM 'f1'
    WITH (ORDER (t1), ROWTERMINATOR = '!', TABLOCK, DATAFILETYPE = 'dts_buffers');

BULK INSERT t1 FROM 'f1'
    WITH (ERRORFILE = 'file1', NO_TRIGGERS);

BULK INSERT t1 FROM 'f1'
    WITH (ROWS_PER_BATCH = 1);

BULK INSERT t1 FROM 'f1'
    WITH (ROWS_PER_BATCH = 100.0);

BULK INSERT t1 FROM 'f1'
    WITH (INCLUDE_HIDDEN);

BULK INSERT t1 FROM 'f1'
    WITH (INCLUDE_HIDDEN, ROWS_PER_BATCH = 100);

INSERT BULK db1.dbo.t1;

INSERT BULK dbo.t1 (c1 INT NOT NULL, c2 CHAR, TIMESTAMP);

INSERT BULK v1 (c1 INT NULL);

INSERT BULK v1
    WITH (ORDER (t1));

INSERT BULK v1
    WITH (CHECK_CONSTRAINTS, FIRE_TRIGGERS, KEEPNULLS, TABLOCK, NO_TRIGGERS);

INSERT BULK v1
    WITH (ROWS_PER_BATCH = 100, KILOBYTES_PER_BATCH = 64);

