CREATE STATISTICS st1
    ON t1(c1);

CREATE STATISTICS st1
    ON [dbo].t1(c1, c2, c3);


GO
CREATE STATISTICS [stat]
    ON t1(c1)
    WITH FULLSCAN;

CREATE STATISTICS [stat]
    ON t1(c1, c2)
    WITH NORECOMPUTE, SAMPLE 12 PERCENT;

CREATE STATISTICS [stat]
    ON t1(c1, c2, c3)
    WITH SAMPLE 12 ROWS, NORECOMPUTE;