CREATE TABLE t1 (
    a1 INT CONSTRAINT C1 FOREIGN KEY REFERENCES TestDB.Gokhan.Employees (c1) ON DELETE CASCADE ON UPDATE NO ACTION NOT FOR REPLICATION,
    a2 INT FOREIGN KEY REFERENCES DB.Sch.T1 (C1) ON DELETE NO ACTION ON UPDATE CASCADE,
    a3 INT CONSTRAINT C2 FOREIGN KEY REFERENCES DB.Sch.T1 ON DELETE CASCADE ON UPDATE NO ACTION,
    a4 INT FOREIGN KEY REFERENCES DB.Sch.T1 ON DELETE CASCADE,
    CONSTRAINT C1 FOREIGN KEY REFERENCES TestDB.Gokhan.Employees (c1, c2) ON DELETE CASCADE ON UPDATE NO ACTION NOT FOR REPLICATION,
    FOREIGN KEY REFERENCES DB.Sch.T1 (C1) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT C2 FOREIGN KEY (a1) REFERENCES DB.Sch.T1 ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT C3 FOREIGN KEY REFERENCES TestDB.Gokhan.Employees (c1, c2) ON DELETE SET NULL ON UPDATE SET DEFAULT NOT FOR REPLICATION,
    FOREIGN KEY REFERENCES TestDB.Gokhan.Employees (c1, c2) ON DELETE SET DEFAULT ON UPDATE SET NULL NOT FOR REPLICATION
);

CREATE TABLE MStracer_history (
    parent_tracer_id  INT      NOT NULL,
    agent_id          INT      NOT NULL,
    subscriber_commit DATETIME NULL CONSTRAINT fk_MStracer_tokens_parent_tracer_id FOREIGN KEY (parent_tracer_id) REFERENCES MStracer_tokens (tracer_id)
);