RESTORE DATABASE db1;

RESTORE DATABASE @var1 FROM @var2;

RESTORE DATABASE db1 FROM TAPE = 'tape1', DISK = 'd:', someDevice;

RESTORE LOG db1;

RESTORE LOG @var2 FROM someDevice;

RESTORE DATABASE db1 FROM @var1
    WITH CHECKSUM, CONTINUE_AFTER_ERROR, ENABLE_BROKER;

RESTORE DATABASE db1 FROM @var1
    WITH NO_CHECKSUM, STOP_ON_ERROR, ERROR_BROKER_CONVERSATIONS;

RESTORE DATABASE db1 FROM @var1
    WITH NEW_BROKER, FILE = 10, KEEP_REPLICATION;

RESTORE DATABASE db1 FROM @var1
    WITH MEDIANAME = @mediaName, MEDIAPASSWORD = 'PLACEHOLDER1';

RESTORE DATABASE db1 FROM @var1
    WITH MOVE 'name1' TO 'name2', PASSWORD = 'PLACEHOLDER1';

RESTORE DATABASE db1 FROM @var1
    WITH RECOVERY, REPLACE, RESTART, RESTRICTED_USER;

RESTORE DATABASE db1 FROM @var1
    WITH NORECOVERY, REWIND, UNLOAD, STATS = 10, STOPAT = @dateVar;

RESTORE DATABASE db1 FROM @var1
    WITH STANDBY = 'someFile', NOREWIND, NOUNLOAD, STATS;

RESTORE DATABASE db1 FROM @var1
    WITH STOPATMARK = 'm1', STOPBEFOREMARK = 'm2' AFTER @somedate;

RESTORE FILELISTONLY FROM @var1;

RESTORE VERIFYONLY FROM TAPE = 'tape1';

RESTORE LABELONLY FROM DISK = 'd:';

RESTORE REWINDONLY FROM someDevice;

RESTORE REWINDONLY FROM @var1
    WITH NORECOVERY;

RESTORE DATABASE AdventureWorks FILE = 'foo' FROM DISK = 'Z:\SQLServerBackups\AdventureWorks.bak'
    WITH NORECOVERY;