CREATE TABLE [dbo].[DatabaseDefinitions] (
    c1   BIGINT            NOT NULL,
    c2   INT               NOT NULL,
    c2a  INT               NOT NULL,
    c3   SMALLINT          NOT NULL,
    c4   TINYINT           NOT NULL,
    c5   BIT               NOT NULL,
    c6   DECIMAL           NOT NULL,
    c6a  DECIMAL           NOT NULL,
    c6b  DECIMAL (10)      NOT NULL,
    c6c  DECIMAL (10)      NOT NULL,
    c6d  DECIMAL (10, 10)  NOT NULL,
    c6e  DECIMAL (10, 10)  NOT NULL,
    c7   NUMERIC           NOT NULL,
    c7a  NUMERIC (10)      NOT NULL,
    c7b  NUMERIC (10, 10)  NOT NULL,
    c8   MONEY             NOT NULL,
    c9   SMALLMONEY        NOT NULL,
    c10  FLOAT             NOT NULL,
    c10a FLOAT (10)        NOT NULL,
    c11  REAL              NOT NULL,
    c12  DATETIME          NOT NULL,
    c13  SMALLDATETIME     NOT NULL,
    c14  CHAR              NOT NULL,
    c15  CHAR (10)         NOT NULL,
    c16  VARCHAR           NOT NULL,
    c17  VARCHAR (10)      NOT NULL,
    c14a CHAR              NOT NULL,
    c15a CHAR (10)         NOT NULL,
    c16a VARCHAR           NOT NULL,
    c17a VARCHAR (10)      NOT NULL,
    c18  VARCHAR           NOT NULL,
    c19  VARCHAR (10)      NOT NULL,
    c20  TEXT              NOT NULL,
    c21  NCHAR             NOT NULL,
    c22  NCHAR (10)        NOT NULL,
    c21a NCHAR             NOT NULL,
    c22a NCHAR (10)        NOT NULL,
    c23  NCHAR             NOT NULL,
    c24  NCHAR (10)        NOT NULL,
    c26  NVARCHAR          NOT NULL,
    c27  NVARCHAR (10)     NOT NULL,
    c26a NVARCHAR          NOT NULL,
    c27a NVARCHAR (10)     NOT NULL,
    c28  NVARCHAR          NOT NULL,
    c29  NVARCHAR (10)     NOT NULL,
    c30  NTEXT             NOT NULL,
    c31  NTEXT             NOT NULL,
    c32  BINARY            NOT NULL,
    c32a BINARY (10)       NOT NULL,
    c33  VARBINARY         NOT NULL,
    c33a VARBINARY (10)    NOT NULL,
    c34  VARBINARY         NOT NULL,
    c34a VARBINARY (10)    NOT NULL,
    c35  IMAGE             NOT NULL,
    c36  SQL_VARIANT       NOT NULL,
    c37  TIMESTAMP         NOT NULL,
    c38  FLOAT             NOT NULL,
    c39  FLOAT (12)        NOT NULL,
    C40  ROWVERSION        NOT NULL,
    C41  UserDefinedType   NOT NULL,
    C42  [UserDefinedType] NOT NULL,
    c43  [mytype]         ,
    c49  XML               NOT NULL,
    c59  NVARCHAR         ,
    c60  NVARCHAR         
);