SET FIPS_FLAGGER OFF, FIPS_FLAGGER 'ENTRY', FIPS_FLAGGER 'INTERMEDIATE';

SET FIPS_FLAGGER 'FULL', QUERY_GOVERNOR_COST_LIMIT 10;

SET LANGUAGE us_english;

SET LANGUAGE 'russian', DATEFORMAT ymd;

SET DATEFIRST @SomeVar;

SET DEADLOCK_PRIORITY low, DEADLOCK_PRIORITY @anotherVar;

SET DEADLOCK_PRIORITY normal;

SET LOCK_TIMEOUT -1;

SET CONTEXT_INFO 0x10000, LOCK_TIMEOUT 1000;

SET NOCOUNT, REMOTE_PROC_TRANSACTIONS OFF;


GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET TEXTSIZE 10;

SET TEXTSIZE 0;

SET TEXTSIZE -100;

SET IDENTITY_INSERT d1.dbo.t1 ON;

SET IDENTITY_INSERT t1 OFF;

SET ERRLVL 1000;

