SET ROWCOUNT 10;

SET ROWCOUNT @myVar;


GO
SET CONCAT_NULL_YIELDS_NULL, CURSOR_CLOSE_ON_COMMIT ON;

SET ANSI_DEFAULTS, ARITHABORT, NUMERIC_ROUNDABORT OFF;

SET STATISTICS IO, PROFILE, TIME ON;

SET STATISTICS PROFILE, TIME OFF;


GO
SET OFFSETS COMPUTE, EXECUTE, FROM, ORDER, PARAM, PROCEDURE, SELECT, STATEMENT, TABLE ON;

SET OFFSETS FROM, ORDER OFF;

SET OFFSETS PARAM ON;