UPDATE STATISTICS t1;

UPDATE STATISTICS t1 (st1);

UPDATE STATISTICS [dbo].t1 (index1, stat1, stat2);


GO
UPDATE STATISTICS t1 (c1)
    WITH ALL;

UPDATE STATISTICS t1 (c1)
    WITH FULLSCAN, RESAMPLE;

UPDATE STATISTICS [dbo].t1 (c1, c2)
    WITH NORECOMPUTE, SAMPLE 1 PERCENT, COLUMNS;

UPDATE STATISTICS t1 (c1, c2, c3)
    WITH SAMPLE 11 ROWS, NORECOMPUTE, INDEX;

UPDATE STATISTICS t1 (c1, c2, c3)
    WITH ROWCOUNT = 100;

UPDATE STATISTICS t1 (c1, c2, c3)
    WITH PAGECOUNT = 2;