
ALTER INDEX ind1
    ON .db..t1 REBUILD PARTITION = 1 WITH(ONLINE = ON);

ALTER INDEX ind1
    ON .db..t1 REBUILD PARTITION = 1 WITH(ONLINE = OFF);

ALTER INDEX ALL
    ON .db..t1 REBUILD PARTITION = 1 WITH(ONLINE = ON);

ALTER INDEX ALL
    ON .db..t1 REBUILD PARTITION = 1 WITH(ONLINE = OFF);

ALTER INDEX ind1
    ON t1 REBUILD WITH(ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 0, ABORT_AFTER_WAIT = NONE)));

ALTER INDEX ind1
    ON t1 REBUILD WITH(ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 1, ABORT_AFTER_WAIT = SELF)));

ALTER INDEX ind1
    ON t1 REBUILD WITH(ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 1, ABORT_AFTER_WAIT = BLOCKERS)));

ALTER INDEX ind1
    ON t1 REBUILD WITH(PAD_INDEX = ON, FILLFACTOR = 50, ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 60, ABORT_AFTER_WAIT = SELF)), MAXDOP = 2, DATA_COMPRESSION = PAGE);

ALTER INDEX ind1
    ON t1 REBUILD PARTITION = 1 WITH(ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 1440 MINUTES, ABORT_AFTER_WAIT = NONE)));

ALTER INDEX ind1
    ON t1 REBUILD PARTITION = 1 WITH(ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 71582 MINUTES, ABORT_AFTER_WAIT = SELF)));

ALTER INDEX ind1
    ON t1 REBUILD PARTITION = 1 WITH(ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 0 MINUTES, ABORT_AFTER_WAIT = BLOCKERS)));

ALTER INDEX ind1
    ON t1 REBUILD PARTITION = 1 WITH(SORT_IN_TEMPDB = ON, ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 0 MINUTES, ABORT_AFTER_WAIT = BLOCKERS)), DATA_COMPRESSION = PAGE);

ALTER INDEX ind1
    ON t1 REBUILD WITH(MAXDOP = 1, DATA_COMPRESSION = COLUMNSTORE);

ALTER INDEX ind1
    ON t1 REBUILD PARTITION = 1 WITH(MAXDOP = 1, DATA_COMPRESSION = COLUMNSTORE_ARCHIVE);

ALTER INDEX ind1
    ON t1 REBUILD PARTITION = ALL WITH(DATA_COMPRESSION = COLUMNSTORE ON PARTITIONS (1, 3), DATA_COMPRESSION = COLUMNSTORE_ARCHIVE ON PARTITIONS (2, 4));