ALTER DATABASE d1
    SET DELAYED_DURABILITY = DISABLED;

ALTER DATABASE d1
    SET DELAYED_DURABILITY = ALLOWED;

ALTER DATABASE d1
    SET DELAYED_DURABILITY = FORCED;

ALTER DATABASE d1
    SET MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT = ON;