BACKUP DATABASE d1
    TO DISK = 'd:'
    WITH FORMAT, COMPRESSION, ENCRYPTION(ALGORITHM = AES_128, SERVER CERTIFICATE = cert1), STATS = 10;

BACKUP DATABASE d1
    TO DISK = 'd:'
    WITH FORMAT, COMPRESSION, ENCRYPTION(ALGORITHM = AES_192, SERVER CERTIFICATE = [cert1]), STATS = 10;

BACKUP DATABASE d1
    TO DISK = 'd:'
    WITH FORMAT, COMPRESSION, ENCRYPTION(ALGORITHM = AES_256, SERVER ASYMMETRIC KEY = key1), STATS = 10;

BACKUP DATABASE d1
    TO DISK = 'd:'
    WITH FORMAT, COMPRESSION, ENCRYPTION(ALGORITHM = TRIPLE_DES_3KEY, SERVER ASYMMETRIC KEY = [key1]), STATS = 10;

BACKUP LOG d1
    TO DISK = 'd:'
    WITH FORMAT, COMPRESSION, ENCRYPTION(ALGORITHM = AES_128, SERVER ASYMMETRIC KEY = key1), STATS = 10;

BACKUP LOG d1
    TO DISK = 'd:'
    WITH FORMAT, COMPRESSION, ENCRYPTION(ALGORITHM = AES_192, SERVER ASYMMETRIC KEY = [key1]), STATS = 10;

BACKUP LOG d1
    TO DISK = 'd:'
    WITH FORMAT, COMPRESSION, ENCRYPTION(ALGORITHM = AES_256, SERVER CERTIFICATE = cert1), STATS = 10;

BACKUP LOG d1
    TO DISK = 'd:'
    WITH FORMAT, COMPRESSION, ENCRYPTION(ALGORITHM = TRIPLE_DES_3KEY, SERVER CERTIFICATE = [cert1]), STATS = 10;