CREATE TABLE T (
    i INT NOT NULL INDEX ix_i NONCLUSTERED HASH WITH (BUCKET_COUNT = 10000),
    k INT NOT NULL
)
WITH (MEMORY_OPTIMIZED = ON, DURABILITY = SCHEMA_ONLY);


GO
CREATE TYPE TT AS TABLE (
    i INT NOT NULL INDEX ix_i NONCLUSTERED HASH WITH (BUCKET_COUNT = 10000),
    k INT NOT NULL)
    WITH (MEMORY_OPTIMIZED = ON);


GO
CREATE TABLE T (
    i INT NOT NULL INDEX ix_i NONCLUSTERED HASH (i, k) WITH (BUCKET_COUNT = 10000),
    k INT NOT NULL
)
WITH (MEMORY_OPTIMIZED = OFF, DURABILITY = SCHEMA_ONLY);


GO
CREATE TYPE TT AS TABLE (
    i INT NOT NULL INDEX ix_i,
    k INT NOT NULL)
    WITH (MEMORY_OPTIMIZED = ON);


GO
CREATE TABLE t (
    c INT INDEX idx WITH (PAD_INDEX = ON, FILLFACTOR = 1, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = ON, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = ON, BUCKET_COUNT = 1000, DATA_COMPRESSION = ROW ON PARTITIONS (1), DATA_COMPRESSION = PAGE ON PARTITIONS (2))
    ON fg FILESTREAM_ON fs_fg
);


GO
CREATE TABLE T (
    [A1] INT NULL INDEX IX1 CLUSTERED,
    [A2] INT NOT NULL INDEX IX2 CLUSTERED
);