COMMIT TRANSACTION WITH (DELAYED_DURABILITY = ON);

COMMIT TRANSACTION WITH (DELAYED_DURABILITY = OFF);

COMMIT TRANSACTION WITH (DELAYED_DURABILITY = ON);

COMMIT TRANSACTION WITH (DELAYED_DURABILITY = OFF);

COMMIT TRANSACTION WITH (DELAYED_DURABILITY = ON);

COMMIT TRANSACTION WITH (DELAYED_DURABILITY = OFF);

COMMIT TRANSACTION myTransaction WITH (DELAYED_DURABILITY = ON);

COMMIT TRANSACTION myTransaction WITH (DELAYED_DURABILITY = OFF);

COMMIT TRANSACTION @tranVariable WITH (DELAYED_DURABILITY = ON);

COMMIT TRANSACTION @tranVariable WITH (DELAYED_DURABILITY = OFF);

