CREATE TABLE t1 (
    c1 INT
)
WITH (MEMORY_OPTIMIZED = ON);

CREATE TABLE t1 (
    c1 INT
)
WITH (DURABILITY = SCHEMA_ONLY);

CREATE TABLE t1 (
    c1 INT
)
WITH (DURABILITY = SCHEMA_AND_DATA, MEMORY_OPTIMIZED = OFF);

CREATE TABLE T (
    i INT NOT NULL,
    k INT NOT NULL,
    INDEX ix_i NONCLUSTERED HASH (i, k) WITH (BUCKET_COUNT = 10000)
)
WITH (MEMORY_OPTIMIZED = ON, DURABILITY = SCHEMA_AND_DATA);


GO
CREATE TYPE TT AS TABLE (
    i INT NOT NULL,
    k INT NOT NULL,
    INDEX ix_i NONCLUSTERED HASH (k, i) WITH (BUCKET_COUNT = 10000))
    WITH (MEMORY_OPTIMIZED = OFF);


GO
CREATE TABLE T (
    i INT NOT NULL,
    k INT NOT NULL,
    INDEX ix_i CLUSTERED (i, k)
)
WITH (MEMORY_OPTIMIZED = ON, DURABILITY = SCHEMA_AND_DATA);


GO
CREATE TYPE TT AS TABLE (
    i INT NOT NULL,
    k INT NOT NULL,
    INDEX ix_i (k, i))
    WITH (MEMORY_OPTIMIZED = OFF);


GO
CREATE TABLE T (
    i INT NOT NULL,
    k INT NOT NULL,
    INDEX ix_i NONCLUSTERED (i, k)
);


GO
CREATE TABLE t (
    c INT,
    INDEX idx (c) WITH (PAD_INDEX = ON, FILLFACTOR = 1, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = ON, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = ON, BUCKET_COUNT = 1000, DATA_COMPRESSION = ROW ON PARTITIONS (1), DATA_COMPRESSION = PAGE ON PARTITIONS (2))
    ON fg FILESTREAM_ON fs_fg
);