CREATE DATABASE d1
    (SERVICE_OBJECTIVE = 'basic');

CREATE DATABASE d1
    (MAXSIZE = 100 MB);

CREATE DATABASE d1
    (EDITION = 'business', SERVICE_OBJECTIVE = 'shared');

CREATE DATABASE d1
    (MAXSIZE = 1 GB, SERVICE_OBJECTIVE = 'shared');

CREATE DATABASE d1
    (MAXSIZE = 100 MB, EDITION = 'web', SERVICE_OBJECTIVE = 'shared');


GO
ALTER DATABASE d1
    MODIFY (SERVICE_OBJECTIVE = 'basic');

ALTER DATABASE d1
    MODIFY (MAXSIZE = 100 MB);

ALTER DATABASE d1
    MODIFY (EDITION = 'basic', SERVICE_OBJECTIVE = 'basic');

ALTER DATABASE d1
    MODIFY (SERVICE_OBJECTIVE = 'basic', MAXSIZE = 100 MB);

ALTER DATABASE d1
    MODIFY (MAXSIZE = 1 GB, EDITION = 'basic', SERVICE_OBJECTIVE = 'basic');


GO
CREATE DATABASE d1
    (SERVICE_OBJECTIVE = ELASTIC_POOL (NAME = [epool1]));

ALTER DATABASE d1
    MODIFY (SERVICE_OBJECTIVE = ELASTIC_POOL (NAME = [epool2]));
