CREATE COLUMNSTORE INDEX cindx
    ON t(c1) WITH (DATA_COMPRESSION = COLUMNSTORE);

CREATE COLUMNSTORE INDEX cindx
    ON t(c1) WITH (DATA_COMPRESSION = COLUMNSTORE_ARCHIVE);

CREATE CLUSTERED COLUMNSTORE INDEX cindx
    ON t WITH (DATA_COMPRESSION = COLUMNSTORE);

CREATE CLUSTERED COLUMNSTORE INDEX cindx
    ON t WITH (DATA_COMPRESSION = COLUMNSTORE_ARCHIVE);

CREATE NONCLUSTERED COLUMNSTORE INDEX cindx
    ON t(c1, c2) WITH (DATA_COMPRESSION = COLUMNSTORE);

CREATE NONCLUSTERED COLUMNSTORE INDEX cindx
    ON t(c1, c2) WITH (DATA_COMPRESSION = COLUMNSTORE_ARCHIVE);

CREATE NONCLUSTERED COLUMNSTORE INDEX cindx
    ON t(c1, c2) WITH (DROP_EXISTING = ON, DATA_COMPRESSION = COLUMNSTORE);

CREATE NONCLUSTERED COLUMNSTORE INDEX cindx
    ON t(c1, c2) WITH (MAXDOP = 12, DATA_COMPRESSION = COLUMNSTORE);

CREATE NONCLUSTERED COLUMNSTORE INDEX cindx
    ON t(c1, c2) WITH (MAXDOP = 12, DROP_EXISTING = ON, DATA_COMPRESSION = COLUMNSTORE);

CREATE CLUSTERED COLUMNSTORE INDEX cindx
    ON t WITH (DROP_EXISTING = ON, DATA_COMPRESSION = COLUMNSTORE);

CREATE CLUSTERED COLUMNSTORE INDEX cindx
    ON t WITH (MAXDOP = 12, DATA_COMPRESSION = COLUMNSTORE);

CREATE CLUSTERED COLUMNSTORE INDEX cindx
    ON t WITH (MAXDOP = 12, DROP_EXISTING = ON, DATA_COMPRESSION = COLUMNSTORE);

CREATE NONCLUSTERED COLUMNSTORE INDEX cindx
    ON t(c1, c2) WITH (DATA_COMPRESSION = COLUMNSTORE)
    ON ps (c1);

CREATE NONCLUSTERED COLUMNSTORE INDEX cindx
    ON t(c1, c2) WITH (MAXDOP = 12, DROP_EXISTING = ON, DATA_COMPRESSION = COLUMNSTORE)
    ON ps (c1);
