SELECT *
FROM MemoryOptimizedTable WITH (SNAPSHOT);

SELECT c1
FROM t1 AS table1 WITH (INDEX (0, 1, ind2), HOLDLOCK, NOLOCK, PAGLOCK, READCOMMITTED, READPAST, READUNCOMMITTED, REPEATABLEREAD, ROWLOCK, SERIALIZABLE, SNAPSHOT, TABLOCK, TABLOCKX, UPDLOCK, XLOCK, NOWAIT), t2 WITH (NOWAIT);

SELECT *
FROM T
OPTION (TABLE HINT(T, SNAPSHOT));