CREATE TABLE T (
    i INT NOT NULL PRIMARY KEY NONCLUSTERED HASH WITH (BUCKET_COUNT = 10000)
)
WITH (MEMORY_OPTIMIZED = ON);


GO
CREATE TYPE TT AS TABLE (
    i INT NOT NULL,
    PRIMARY KEY NONCLUSTERED HASH (i) WITH (BUCKET_COUNT = 1000))
    WITH (MEMORY_OPTIMIZED = ON);


GO
CREATE TABLE T (
    i INT NOT NULL UNIQUE NONCLUSTERED HASH WITH (BUCKET_COUNT = 10000)
)
WITH (MEMORY_OPTIMIZED = ON);


GO
CREATE TABLE T (
    i INT NOT NULL UNIQUE CLUSTERED
);


GO
CREATE TYPE TT AS TABLE (
    i INT NOT NULL,
    PRIMARY KEY NONCLUSTERED (i));