ADD SIGNATURE TO HumanResources.uspUpdateEmployeeLogin
    BY CERTIFICATE HumanResourcesDP;

DROP SIGNATURE FROM HumanResources.uspUpdateEmployeeLogin
    BY CERTIFICATE HumanResourcesDP;

ADD COUNTER SIGNATURE TO ASSEMBLY::a1
    BY ASYMMETRIC KEY ask1 WITH PASSWORD = 'PLACEHOLDER1';

DROP COUNTER SIGNATURE FROM OBJECT::dbo.o1
    BY ASYMMETRIC KEY ask2 WITH SIGNATURE = 0x10;

ADD SIGNATURE TO DATABASE::db1
    BY PASSWORD = 'PLACEHOLDER2', CERTIFICATE cert1 WITH SIGNATURE = 0x20, ASYMMETRIC KEY ask3;

