ALTER FULLTEXT CATALOG c1 REBUILD;

ALTER FULLTEXT CATALOG c1 REBUILD WITH ACCENT_SENSITIVITY = ON;

ALTER FULLTEXT CATALOG c1 REBUILD WITH ACCENT_SENSITIVITY = OFF;

ALTER FULLTEXT CATALOG c1 REORGANIZE;

ALTER FULLTEXT CATALOG c1 AS DEFAULT;

