ALTER CERTIFICATE c1 REMOVE PRIVATE KEY;

ALTER CERTIFICATE c1 WITH ACTIVE FOR BEGIN_DIALOG = ON;

ALTER CERTIFICATE c1 WITH PRIVATE KEY (FILE = 'zzz');

ALTER CERTIFICATE c1 REMOVE ATTESTED OPTION;

ALTER CERTIFICATE c1 ATTESTED BY 'zzz';

