ALTER DATABASE d1
    MODIFY FILEGROUP fg1 READ_ONLY 
    WITH ROLLBACK AFTER 10 SECONDS;

ALTER DATABASE d1
    MODIFY FILEGROUP fg1 READWRITE 
    WITH ROLLBACK AFTER 10 SECONDS;

ALTER DATABASE d1
    MODIFY FILEGROUP fg1 READ_WRITE 
    WITH ROLLBACK IMMEDIATE;

ALTER DATABASE d1
    MODIFY FILEGROUP fg1 READ_WRITE 
    WITH NO_WAIT;

ALTER DATABASE AdventureWorks
    ADD LOG FILE (FILENAME = 'log2', NAME = test1log2), (FILENAME = 'log3', NAME = test1log2) TO FILEGROUP FG;

ALTER DATABASE db1
    MODIFY FILE (OFFLINE, NAME = n1, NEWNAME = n2);

ALTER DATABASE db1
    REBUILD LOG;

ALTER DATABASE db1
    REBUILD LOG ON (NAME = 'n1', FILENAME = 'zzz');


GO
CREATE DATABASE Archive
    ON 
    (FILENAME = 'zzz') FOR ATTACH_REBUILD_LOG
    WITH TRUSTWORTHY OFF;

CREATE DATABASE Archive
    ON 
    (FILENAME = 'zzz') FOR ATTACH_FORCE_REBUILD_LOG
    WITH TRUSTWORTHY OFF, DB_CHAINING ON;

CREATE DATABASE Archive
    ON 
    (FILENAME = 'zzz') FOR ATTACH
    WITH ENABLE_BROKER;

CREATE DATABASE Archive
    ON 
    (FILENAME = 'zzz') FOR ATTACH
    WITH NEW_BROKER;

CREATE DATABASE Archive
    ON 
    (FILENAME = 'zzz') FOR ATTACH
    WITH ERROR_BROKER_CONVERSATIONS;

CREATE DATABASE sales_snapshot0600
    ON 
    (NAME = N1, FILENAME = 'N1')
    AS SNAPSHOT OF Sales;

