ALTER TABLE t1
    ADD c2 INT            NULL,
        c3 AS             -c1 UNIQUE,
        c4 INT            DEFAULT 23 WITH VALUES,
        c5 INT            DEFAULT 23,
        c6 NVARCHAR (100) COLLATE someCollatation, 
        CHECK (c1 > 10),
        CONSTRAINT cs1 DEFAULT 20 FOR c1,
        CONSTRAINT cs2 DEFAULT 20 FOR c10 WITH VALUES,
        CONSTRAINT cs3 CHECK (c1 < 100);

ALTER TABLE t1 WITH NOCHECK
    ADD CONSTRAINT cs1 DEFAULT 10 FOR c1;

ALTER TABLE t1 WITH CHECK
    ADD CONSTRAINT cs1 DEFAULT 10 FOR c1;

ALTER TABLE t1 WITH CHECK
    ADD CONSTRAINT C1 FOREIGN KEY REFERENCES DB.Sch.T1 (C1) ON DELETE CASCADE ON UPDATE NO ACTION NOT FOR REPLICATION;

ALTER TABLE [dbo].[book_ratings] WITH CHECK
    ADD CONSTRAINT [book_ratings_title_id] FOREIGN KEY ([title_id]) REFERENCES [titles] ([title_id]) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE t1 WITH CHECK
    ADD CONSTRAINT C1 UNIQUE CLUSTERED (A1 ASC, A2 DESC) WITH (FILLFACTOR = 25) ON [DEFAULT];

ALTER TABLE t1 WITH CHECK
    ADD CONSTRAINT C1 PRIMARY KEY CLUSTERED (A1 ASC, A2 DESC) WITH (FILLFACTOR = 25);