ALTER INDEX ind1
    ON .db..t1 REBUILD;

ALTER INDEX ALL
    ON .db..t1 REBUILD WITH(PAD_INDEX = ON);

ALTER INDEX ind1
    ON .db..t1 REBUILD PARTITION = 1 + 2 WITH(SORT_IN_TEMPDB = ON, MAXDOP = 12);

ALTER INDEX ind1
    ON t1 REORGANIZE;

ALTER INDEX ind1
    ON .db..t1 REORGANIZE WITH(LOB_COMPACTION = ON);

ALTER INDEX ind1
    ON .db..t1 REORGANIZE PARTITION = 1 + 2 WITH(LOB_COMPACTION = ON);

ALTER INDEX ALL
    ON t1 DISABLE;

ALTER INDEX ind1
    ON t1 SET (ALLOW_PAGE_LOCKS = ON);

ALTER INDEX ind1
    ON t1 SET (ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

