ALTER ASYMMETRIC KEY a1 REMOVE PRIVATE KEY;

ALTER ASYMMETRIC KEY a1 REMOVE ATTESTED OPTION;

ALTER ASYMMETRIC KEY a1 ATTESTED BY 'zzz';

ALTER ASYMMETRIC KEY a1 WITH PRIVATE KEY (ENCRYPTION BY PASSWORD = 'pw1');

ALTER ASYMMETRIC KEY a1 WITH PRIVATE KEY (DECRYPTION BY PASSWORD = 'pw1');

ALTER ASYMMETRIC KEY a1 WITH PRIVATE KEY (DECRYPTION BY PASSWORD = 'pw1', ENCRYPTION BY PASSWORD = 'pw2');

