ALTER CREDENTIAL c1
    WITH IDENTITY = 'id1';

ALTER CREDENTIAL c1
    WITH IDENTITY = 'id1', SECRET = 'secret';


GO
CREATE CREDENTIAL c1
    WITH IDENTITY = 'id1';

CREATE CREDENTIAL c1
    WITH IDENTITY = 'id1', SECRET = 'secret';

