ALTER MASTER KEY REGENERATE WITH ENCRYPTION BY PASSWORD = 'pw1';

ALTER MASTER KEY FORCE REGENERATE WITH ENCRYPTION BY PASSWORD = 'pw1';

ALTER MASTER KEY ADD ENCRYPTION BY PASSWORD = 'pw1';

ALTER MASTER KEY DROP ENCRYPTION BY PASSWORD = 'pw1';

ALTER MASTER KEY ADD ENCRYPTION BY SERVICE MASTER KEY;

ALTER MASTER KEY DROP ENCRYPTION BY SERVICE MASTER KEY;

