ALTER DATABASE d1
    SET EMERGENCY;

ALTER DATABASE d1
    SET DB_CHAINING ON,
        TRUSTWORTHY OFF;

ALTER DATABASE d1
    SET TRUSTWORTHY ON,
        DB_CHAINING OFF;

ALTER DATABASE d1
    SET AUTO_UPDATE_STATISTICS_ASYNC OFF;

ALTER DATABASE d1
    SET PAGE_VERIFY CHECKSUM,
        PAGE_VERIFY NONE,
        PAGE_VERIFY TORN_PAGE_DETECTION;

ALTER DATABASE d1
    SET PARTNER = 'some_server',
        PARTNER FAILOVER;

ALTER DATABASE d1
    SET WITNESS = 'witness',
        PARTNER FORCE_SERVICE_ALLOW_DATA_LOSS,
        PARTNER RESUME;

ALTER DATABASE d1
    SET ERROR_BROKER_CONVERSATIONS,
        PARTNER SAFETY FULL,
        PARTNER SUSPEND;

ALTER DATABASE d1
    SET ENABLE_BROKER,
        PARTNER SAFETY OFF,
        PARTNER TIMEOUT 10;

ALTER DATABASE d1
    SET DISABLE_BROKER,
        WITNESS  OFF;

ALTER DATABASE d1
    SET NEW_BROKER;

ALTER DATABASE d1
    SET DATE_CORRELATION_OPTIMIZATION ON,
        PARAMETERIZATION SIMPLE;

ALTER DATABASE d1
    SET PARAMETERIZATION FORCED,
        DATE_CORRELATION_OPTIMIZATION OFF;

ALTER DATABASE d1
    SET ALLOW_SNAPSHOT_ISOLATION ON,
        READ_COMMITTED_SNAPSHOT ON;

ALTER DATABASE d1
    SET READ_COMMITTED_SNAPSHOT OFF,
        ALLOW_SNAPSHOT_ISOLATION OFF;

ALTER DATABASE d1
    SET SUPPLEMENTAL_LOGGING OFF;

