ALTER TABLE t1 DROP CONSTRAINT cs1
    WITH (ONLINE = OFF, MOVE TO myFilegroup), cs2
    WITH (MAXDOP = 21);


GO
ALTER TABLE t1 DROP COLUMN c1, CONSTRAINT c21
    WITH (ONLINE = ON), cs1
    WITH (MOVE TO 'default' (col1), ONLINE = OFF, MAXDOP = 21);

