ALTER SERVICE MASTER KEY REGENERATE;

ALTER SERVICE MASTER KEY FORCE REGENERATE;

ALTER SERVICE MASTER KEY WITH NEW_ACCOUNT = 'AdvWorks\Sandeep', NEW_PASSWORD = 'PLACEHOLDER2';

ALTER SERVICE MASTER KEY WITH OLD_ACCOUNT = 'AdvWorks\MiraG', OLD_PASSWORD = 'PLACEHOLDER1';

