ALTER PARTITION FUNCTION f1( )
    SPLIT;

ALTER PARTITION FUNCTION f1( )
    MERGE;

ALTER PARTITION FUNCTION f1( )
    SPLIT RANGE (10);

ALTER PARTITION FUNCTION f1( )
    MERGE RANGE (10);

ALTER PARTITION SCHEME s1 NEXT USED;

ALTER PARTITION SCHEME s1 NEXT USED fg1;

ALTER PARTITION SCHEME s1 NEXT USED 'zzz';

