CREATE ASYMMETRIC KEY k1
    AUTHORIZATION a1
     FROM FILE = 'zzz';

CREATE ASYMMETRIC KEY k1
     FROM EXECUTABLE FILE = 'yyy';

CREATE ASYMMETRIC KEY k1
     FROM ASSEMBLY aaa
    ENCRYPTION BY PASSWORD = 'p1';


GO
CREATE ASYMMETRIC KEY k1
    WITH ALGORITHM = RC2;

CREATE ASYMMETRIC KEY k1
    WITH ALGORITHM = RC4;

CREATE ASYMMETRIC KEY k1
    WITH ALGORITHM = RC4_128;

CREATE ASYMMETRIC KEY k1
    WITH ALGORITHM = DES;

CREATE ASYMMETRIC KEY k1
    WITH ALGORITHM = TRIPLE_DES;

CREATE ASYMMETRIC KEY k1
    WITH ALGORITHM = DESX;

CREATE ASYMMETRIC KEY k1
    WITH ALGORITHM = AES_128;

CREATE ASYMMETRIC KEY k1
    WITH ALGORITHM = AES_192;

CREATE ASYMMETRIC KEY k1
    WITH ALGORITHM = AES_256;

CREATE ASYMMETRIC KEY k1
    WITH ALGORITHM = RSA_512;

CREATE ASYMMETRIC KEY k1
    WITH ALGORITHM = RSA_1024;

CREATE ASYMMETRIC KEY k1
    WITH ALGORITHM = RSA_2048;


GO
ALTER ASYMMETRIC KEY a1 REMOVE PRIVATE KEY;

ALTER ASYMMETRIC KEY a1 REMOVE ATTESTED OPTION;

ALTER ASYMMETRIC KEY a1 ATTESTED BY 'zzz';

ALTER ASYMMETRIC KEY a1 WITH PRIVATE KEY (ENCRYPTION BY PASSWORD = 'pw1');

ALTER ASYMMETRIC KEY a1 WITH PRIVATE KEY (DECRYPTION BY PASSWORD = 'pw1');

ALTER ASYMMETRIC KEY a1 WITH PRIVATE KEY (DECRYPTION BY PASSWORD = 'pw1', ENCRYPTION BY PASSWORD = 'pw2');


GO
DROP ASYMMETRIC KEY k1;