BACKUP CERTIFICATE c1 TO FILE = 'f1';

BACKUP CERTIFICATE c1 TO FILE = 'f1'
    WITH PRIVATE KEY (FILE = 'f2');

BACKUP CERTIFICATE c1 TO FILE = 'f1'
    WITH PRIVATE KEY (FILE = 'f2', DECRYPTION BY PASSWORD = 'd1', ENCRYPTION BY PASSWORD = 'e1');

