CREATE PARTITION FUNCTION myRangePF1(INT)
    AS RANGE LEFT
    FOR VALUES (1, 100, 1000);

CREATE PARTITION FUNCTION myRangePF1(CHAR (10) COLLATE Estonian_CS_AS)
    AS RANGE RIGHT
    FOR VALUES (1);

