CREATE MESSAGE TYPE [//Adventure-Works.com/Expenses/SubmitExpense]
    VALIDATION = WELL_FORMED_XML;

CREATE MESSAGE TYPE m1
    AUTHORIZATION zzz
    VALIDATION = NONE;

CREATE MESSAGE TYPE m1
    VALIDATION = EMPTY;

CREATE MESSAGE TYPE m1
    VALIDATION = VALID_XML WITH SCHEMA COLLECTION sch1;