CREATE TRIGGER reminder
    ON t1
    WITH EXECUTE AS CALLER
    FOR INSERT
    AS  EXTERNAL NAME a.b.c


GO
CREATE TRIGGER reminder
    ON t1
    WITH ENCRYPTION, EXECUTE AS SELF
    AFTER UPDATE, DELETE, INSERT
    NOT FOR REPLICATION
    AS  EXTERNAL NAME a.b.c


GO
CREATE TRIGGER reminder
    ON t1
    WITH EXECUTE AS OWNER, ENCRYPTION
    INSTEAD OF DELETE, INSERT
    AS PRINT 'hi';


GO
CREATE TRIGGER reminder
    ON t1
    WITH EXECUTE AS 'dbo'
    FOR DELETE
    NOT FOR REPLICATION
    AS PRINT 'hi';


GO
CREATE TRIGGER reminder
    ON t1
    WITH ENCRYPTION
    INSTEAD OF DELETE
    AS PRINT 'hi';


GO
CREATE TRIGGER reminder
    ON ALL SERVER
    WITH EXECUTE AS CALLER
    FOR DENY_DATABASE
    AS  EXTERNAL NAME a.b.c


GO
CREATE TRIGGER reminder
    ON DATABASE
    WITH ENCRYPTION, EXECUTE AS SELF
    AFTER DROP_FUNCTION, CREATE_FUNCTION
    AS  EXTERNAL NAME a.b.c


GO
CREATE TRIGGER reminder
    ON DATABASE
    WITH EXECUTE AS 'dbo'
    FOR ALTER_ASSEMBLY, DROP_FUNCTION, CREATE_FUNCTION
    AS PRINT 'hi';

