CREATE PROCEDURE p1
AS
BEGIN
    BEGIN TRY
        END CONVERSATION 10;
        ENABLE TRIGGER t1
            ON o1;
    END TRY
    BEGIN CATCH
        END CONVERSATION 10;
        ENABLE TRIGGER t1
            ON o1;
    END CATCH
    BEGIN
        END CONVERSATION 10;
        ENABLE TRIGGER t1
            ON o1;
    END
    END CONVERSATION 10;
    ENABLE TRIGGER t1
        ON o1;
    BEGIN TRY
        DECLARE @v1 AS INT;
    END TRY
    BEGIN CATCH
    END CATCH
END
END CONVERSATION 1
    WITH ERROR = @v1 DESCRIPTION = 'd1';
END CONVERSATION 1
    WITH ERROR = 10 DESCRIPTION = 'd2';
END CONVERSATION 1
    WITH CLEANUP;