CREATE FULLTEXT INDEX ON ...t1
    KEY INDEX [i1];

CREATE FULLTEXT INDEX ON t1
    KEY INDEX [i1]
    ON fc;

CREATE FULLTEXT INDEX ON t1
    (c1)
    KEY INDEX [i1]
    ON fc;

CREATE FULLTEXT INDEX ON t1
    (c1 TYPE COLUMN [binary])
    KEY INDEX [i1]
    ON fc;

CREATE FULLTEXT INDEX ON t1
    (c1 LANGUAGE 0x413)
    KEY INDEX [i1]
    ON fc;

CREATE FULLTEXT INDEX ON t1
    (c1, c2 LANGUAGE 1043, c3 TYPE COLUMN varchar LANGUAGE 'english')
    KEY INDEX [i1]
    ON fc;

CREATE FULLTEXT INDEX ON [dbo].[CatalogA_table]
    ([column1] LANGUAGE [English])
    KEY INDEX [PK_CatalogA_table]
    ON [CatalogA]
    WITH CHANGE_TRACKING OFF;

CREATE FULLTEXT INDEX ON [dbo].[CatalogA_table]
    ([column1] LANGUAGE English)
    KEY INDEX [PK_CatalogA_table]
    ON [CatalogA]
    WITH CHANGE_TRACKING OFF;

CREATE FULLTEXT INDEX ON t1
    (c1 TYPE COLUMN [binary])
    KEY INDEX [i1]
    WITH CHANGE_TRACKING MANUAL;

CREATE FULLTEXT INDEX ON t1
    (c1 TYPE COLUMN [binary])
    KEY INDEX [i1]
    WITH CHANGE_TRACKING OFF;

CREATE FULLTEXT INDEX ON t1
    (c1 TYPE COLUMN [binary])
    KEY INDEX [i1]
    ON fc
    WITH CHANGE_TRACKING AUTO;

CREATE FULLTEXT INDEX ON t1
    (c1 TYPE COLUMN [binary])
    KEY INDEX [i1]
    WITH CHANGE_TRACKING OFF, NO POPULATION;


GO
ALTER FULLTEXT INDEX ON dbo.t1 ENABLE;

ALTER FULLTEXT INDEX ON t1 DISABLE;

ALTER FULLTEXT INDEX ON t1 SET CHANGE_TRACKING MANUAL;

ALTER FULLTEXT INDEX ON t1 SET CHANGE_TRACKING AUTO;

ALTER FULLTEXT INDEX ON t1 SET CHANGE_TRACKING OFF;

ALTER FULLTEXT INDEX ON t1 ADD (c1, c2 TYPE COLUMN int, c3 LANGUAGE 1043);

ALTER FULLTEXT INDEX ON t1 ADD (c1, c2 TYPE COLUMN int, c3 LANGUAGE 'THAI');

ALTER FULLTEXT INDEX ON t1 ADD (c1) WITH NO POPULATION;

ALTER FULLTEXT INDEX ON t1 DROP (c1, c2) WITH NO POPULATION;

ALTER FULLTEXT INDEX ON t1 DROP (c1);

ALTER FULLTEXT INDEX ON t1 START FULL POPULATION;

ALTER FULLTEXT INDEX ON t1 START INCREMENTAL POPULATION;

ALTER FULLTEXT INDEX ON t1 START UPDATE POPULATION;

ALTER FULLTEXT INDEX ON t1 STOP POPULATION;

ALTER FULLTEXT INDEX ON t1 PAUSE POPULATION;

ALTER FULLTEXT INDEX ON t1 RESUME POPULATION;


GO
DROP FULLTEXT INDEX ON dbo.t1;

DROP FULLTEXT INDEX ON t1;