INSERT TOP (2.5) PERCENT @v1
DEFAULT VALUES;

INSERT TOP (SELECT *
            FROM t2) @v1
DEFAULT VALUES;


GO
INSERT t1
OUTPUT a.b.c1 AS [c2], c2
DEFAULT VALUES;

INSERT table1 WITH (HOLDLOCK)
OUTPUT c1, c2 INTO @t1 (c1)
SELECT *
FROM t1;

INSERT @v2
OUTPUT c1, c2 INTO @t1
OUTPUT c1 AS [C1], 12 * 12 AS [144]
VALUES (10, 20);