CREATE LOGIN l1
    WITH PASSWORD = 'p1';

CREATE LOGIN l1
    WITH PASSWORD = 'p1' HASHED, SID = 0x10, DEFAULT_DATABASE = db1, CHECK_EXPIRATION = ON;

CREATE LOGIN l1
    WITH PASSWORD = 0x234 HASHED, SID = 0x10, DEFAULT_DATABASE = db1, CHECK_EXPIRATION = ON;

CREATE LOGIN l1
    WITH PASSWORD = 'p1' HASHED MUST_CHANGE, DEFAULT_LANGUAGE = l1, CHECK_POLICY = OFF, CREDENTIAL = c1;

CREATE LOGIN [l1]
    FROM WINDOWS;

CREATE LOGIN [l1]
    FROM WINDOWS WITH DEFAULT_DATABASE = db1, DEFAULT_LANGUAGE = l1;

CREATE LOGIN l1
    FROM CERTIFICATE c1;

CREATE LOGIN l1
    FROM CERTIFICATE c1 WITH CREDENTIAL = cr1;

CREATE LOGIN l1
    FROM ASYMMETRIC KEY k1;

CREATE LOGIN l1
    FROM ASYMMETRIC KEY k1 WITH CREDENTIAL = cr1;


GO
ALTER LOGIN l1 ENABLE;

ALTER LOGIN l1 DISABLE;

ALTER LOGIN l1 WITH PASSWORD = 'PLACEHOLDER1';

ALTER LOGIN l1 WITH PASSWORD = 'PLACEHOLDER1' OLD_PASSWORD = 'PLACEHOLDER2';

ALTER LOGIN l1 WITH PASSWORD = 'PLACEHOLDER1' MUST_CHANGE;

ALTER LOGIN l1 WITH PASSWORD = 'PLACEHOLDER1' MUST_CHANGE UNLOCK;

ALTER LOGIN l1 WITH PASSWORD = 'PLACEHOLDER1' UNLOCK;

ALTER LOGIN l1 WITH PASSWORD = N'PLACEHOLDER1' HASHED;

ALTER LOGIN l1 WITH PASSWORD = 0x00012 HASHED;

ALTER LOGIN l1 WITH PASSWORD = 0x012 OLD_PASSWORD = 'PLACEHOLDER2';

ALTER LOGIN l1 WITH PASSWORD = 'PLACEHOLDER1' MUST_CHANGE HASHED UNLOCK;

ALTER LOGIN l1 WITH NO CREDENTIAL, DEFAULT_DATABASE = db1, DEFAULT_LANGUAGE = l1;

ALTER LOGIN l1 WITH NAME = l2, CHECK_POLICY = ON, CHECK_EXPIRATION = OFF;

ALTER LOGIN l1 WITH CREDENTIAL = cr1;


GO
DROP LOGIN l1;
