OPEN SYMMETRIC KEY [key1] DECRYPTION BY CERTIFICATE c1;

OPEN SYMMETRIC KEY [key1] DECRYPTION BY CERTIFICATE [c1] WITH PASSWORD = 'p1';

OPEN SYMMETRIC KEY [key1] DECRYPTION BY ASYMMETRIC KEY [ak1];

OPEN SYMMETRIC KEY [key1] DECRYPTION BY ASYMMETRIC KEY ak1 WITH PASSWORD = N'p1';

OPEN SYMMETRIC KEY [key1] DECRYPTION BY SYMMETRIC KEY sk1;

OPEN SYMMETRIC KEY [key1] DECRYPTION BY PASSWORD = 'password';

