CREATE QUEUE dbo.q1;

CREATE QUEUE [q1]
    ON [filegroup];

CREATE QUEUE [q1]
    ON 'filegroup';

CREATE QUEUE [q1]
    ON fileGroup;

CREATE QUEUE db.dbo.q1
    WITH STATUS = OFF;

CREATE QUEUE q1
    WITH STATUS = ON, RETENTION = OFF, ACTIVATION (STATUS = ON, PROCEDURE_NAME = dbo..p1, MAX_QUEUE_READERS = 23, EXECUTE AS SELF);

CREATE QUEUE q1
    WITH STATUS = ON, RETENTION = OFF, ACTIVATION (STATUS = ON, PROCEDURE_NAME = dbo..p1, MAX_QUEUE_READERS = 23, EXECUTE AS OWNER)
    ON filegroup;


GO
ALTER QUEUE dbo.q1
    WITH ACTIVATION (DROP);

ALTER QUEUE dbo.q1
    WITH STATUS = ON, ACTIVATION (DROP);


GO
ALTER QUEUE ExpenseQueue
    WITH ACTIVATION (PROCEDURE_NAME = dbo.qspProcessExpenseQueue, EXECUTE AS 'dbo');