CREATE ROUTE r1
    WITH BROKER_INSTANCE = 'b1';

CREATE ROUTE [r1]
    AUTHORIZATION [dbo]
    WITH BROKER_INSTANCE = 'b1';

CREATE ROUTE r1
    WITH SERVICE_NAME = 's1';

CREATE ROUTE r1
    AUTHORIZATION [dbo]
    WITH BROKER_INSTANCE = 'b1', LIFETIME = 23, ADDRESS = 'a1', MIRROR_ADDRESS = 'ma1', SERVICE_NAME = 's1';


GO
ALTER ROUTE r1
    WITH BROKER_INSTANCE = 'b1', LIFETIME = 23, ADDRESS = 'a1', MIRROR_ADDRESS = 'ma1', SERVICE_NAME = 's1';

