SELECT *
FROM OPENROWSET (BULK 'df1', SINGLE_BLOB) AS a(c1);


GO
SELECT *
FROM OPENROWSET (BULK 'df1', SINGLE_CLOB, LASTROW = 10) AS a(c1, c2);


GO
SELECT *
FROM OPENROWSET (BULK 'df1', SINGLE_NCLOB, ERRORFILE = 'ef1') AS a;