GRANT SELECT
    ON ..t1 TO PUBLIC;

GRANT INSERT
    ON ..t1 (c1) TO PUBLIC;

GRANT ALL PRIVILEGES
    ON ..t1 (c1, c2, c3) TO PUBLIC;

GRANT ALL, SELECT (c1, c2), INSERT, DELETE, UPDATE, EXEC, EXECUTE, REFERENCES (c1, c2)
    ON t2 TO guest;

GRANT CREATE DATABASE TO PUBLIC
    AS [clause];

GRANT CREATE DEFAULT TO [guest];

GRANT CREATE FUNCTION TO [guest];

GRANT CREATE PROCEDURE TO [guest];

GRANT CREATE RULE TO [guest];

GRANT CREATE TABLE TO [guest];

GRANT CREATE VIEW TO [guest];

GRANT BACKUP DATABASE TO [guest];

GRANT BACKUP LOG TO [guest];

GRANT CREATE DATABASE, CREATE DEFAULT, CREATE FUNCTION, CREATE PROCEDURE, CREATE RULE, CREATE TABLE, CREATE VIEW, BACKUP DATABASE, BACKUP LOG TO [guest];

GRANT ALL TO NULL
    WITH GRANT OPTION;

GRANT all TO PUBLIC
    WITH GRANT OPTION
    AS t1;

DENY select
    ON t2 TO NULL;

DENY create view TO [guest];

DENY all TO PUBLIC CASCADE;

REVOKE GRANT OPTION FOR select
    ON t2 TO NULL;

REVOKE create view TO [guest];

REVOKE create view TO [guest]
    AS role1;

REVOKE all TO PUBLIC CASCADE;

REVOKE all TO PUBLIC CASCADE
    AS [group 2];