CREATE SYMMETRIC KEY k1
    AUTHORIZATION zzz
    WITH ALGORITHM = DES
    ENCRYPTION BY CERTIFICATE c1;

CREATE SYMMETRIC KEY k1
    WITH KEY_SOURCE = 'ks', IDENTITY_VALUE = 'iv', ALGORITHM = RC2
    ENCRYPTION BY PASSWORD = 'p1';

CREATE SYMMETRIC KEY k1
    WITH ALGORITHM = RC4
    ENCRYPTION BY CERTIFICATE c1, PASSWORD = 'p1', SYMMETRIC KEY s1, ASYMMETRIC KEY as1;


GO
ALTER SYMMETRIC KEY k1 DROP ENCRYPTION BY PASSWORD = 'p1';

ALTER SYMMETRIC KEY k1 ADD ENCRYPTION BY PASSWORD = 'p1', SYMMETRIC KEY s1;


GO
DROP SYMMETRIC KEY k1;