CREATE USER u1;

CREATE USER [u1] FOR LOGIN [l1];

CREATE USER [u1] FOR LOGIN l1;

CREATE USER u1 FOR CERTIFICATE c1;

CREATE USER u1 FOR ASYMMETRIC KEY a1;

CREATE USER u1 WITHOUT LOGIN;

CREATE USER u1
    WITH DEFAULT_SCHEMA = dbo;

CREATE USER u1 FOR CERTIFICATE c1
    WITH DEFAULT_SCHEMA = [dbo];

CREATE USER u1 FOR ASYMMETRIC KEY a1
    WITH DEFAULT_SCHEMA = dbo;


GO
ALTER USER u1
    WITH DEFAULT_SCHEMA = dbo;

ALTER USER u1
    WITH NAME = newName;

ALTER USER u1
    WITH NAME = newName, DEFAULT_SCHEMA = dbo, LOGIN = l1;