ALTER INDEX ind1
    ON .db..t1 REORGANIZE WITH(COMPRESS_ALL_ROW_GROUPS = ON);

ALTER INDEX ind1
    ON .db..t1 REORGANIZE WITH(COMPRESS_ALL_ROW_GROUPS = OFF);

ALTER INDEX ind1
    ON .db..t1 REORGANIZE PARTITION = 1 + 2 WITH(COMPRESS_ALL_ROW_GROUPS = ON);

ALTER INDEX ind1
    ON .db..t1 REORGANIZE PARTITION = 1 + 2 WITH(COMPRESS_ALL_ROW_GROUPS = OFF);

ALTER INDEX ind1
    ON .db..t1 SET (COMPRESSION_DELAY = 0 MINUTE);

ALTER INDEX ind1
    ON .db..t1 SET (COMPRESSION_DELAY = 27);

ALTER INDEX ind1
    ON .db..t1 SET (COMPRESSION_DELAY = 10080 MINUTES);