ALTER DATABASE db
    SET QUERY_STORE = ON;

ALTER DATABASE db
    SET QUERY_STORE = OFF;

ALTER DATABASE db
    SET QUERY_STORE CLEAR;

ALTER DATABASE db
    SET QUERY_STORE CLEAR ALL;

ALTER DATABASE db
    SET QUERY_STORE (DESIRED_STATE = READ_WRITE);

ALTER DATABASE db
    SET QUERY_STORE (DESIRED_STATE = READ_ONLY);

ALTER DATABASE db
    SET QUERY_STORE (OPERATION_MODE = READ_WRITE);

ALTER DATABASE db
    SET QUERY_STORE (OPERATION_MODE = READ_ONLY);

ALTER DATABASE db
    SET QUERY_STORE (QUERY_CAPTURE_MODE = NONE);

ALTER DATABASE db
    SET QUERY_STORE (QUERY_CAPTURE_MODE = AUTO);

ALTER DATABASE db
    SET QUERY_STORE (QUERY_CAPTURE_MODE = ALL);

ALTER DATABASE db
    SET QUERY_STORE (SIZE_BASED_CLEANUP_MODE = OFF);

ALTER DATABASE db
    SET QUERY_STORE (SIZE_BASED_CLEANUP_MODE = AUTO);

ALTER DATABASE db
    SET QUERY_STORE (DATA_FLUSH_INTERVAL_SECONDS = 25000);

ALTER DATABASE db
    SET QUERY_STORE (DATA_FLUSH_INTERVAL_SECONDS = 1000);

ALTER DATABASE db
    SET QUERY_STORE (INTERVAL_LENGTH_MINUTES = 15);

ALTER DATABASE db
    SET QUERY_STORE (MAX_STORAGE_SIZE_MB = 2000);

ALTER DATABASE db
    SET QUERY_STORE (MAX_PLANS_PER_QUERY = 200);

ALTER DATABASE db
    SET QUERY_STORE (CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 367));

ALTER DATABASE db
    SET QUERY_STORE (DESIRED_STATE = READ_ONLY, QUERY_CAPTURE_MODE = ALL, SIZE_BASED_CLEANUP_MODE = OFF, INTERVAL_LENGTH_MINUTES = 100, MAX_STORAGE_SIZE_MB = 1000, MAX_PLANS_PER_QUERY = 200, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 367));

ALTER DATABASE db
    SET QUERY_STORE = ON(DESIRED_STATE = READ_ONLY, QUERY_CAPTURE_MODE = ALL, SIZE_BASED_CLEANUP_MODE = OFF, INTERVAL_LENGTH_MINUTES = 100, MAX_STORAGE_SIZE_MB = 1000, MAX_PLANS_PER_QUERY = 200, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 367));

ALTER DATABASE db
    SET MIXED_PAGE_ALLOCATION ON;

ALTER DATABASE db
    SET MIXED_PAGE_ALLOCATION OFF;