ALTER DATABASE d1
    MODIFY FILEGROUP [primary] AUTOGROW_ALL_FILES;

ALTER DATABASE d1
    MODIFY FILEGROUP [primary] AUTOGROW_SINGLE_FILE;

ALTER DATABASE d1
    MODIFY FILEGROUP fg1 AUTOGROW_ALL_FILES;

ALTER DATABASE d1
    MODIFY FILEGROUP fg1 AUTOGROW_SINGLE_FILE;