ALTER TABLE T SET (SYSTEM_VERSIONING = OFF);


GO
ALTER TABLE T
    ADD PERIOD FOR SYSTEM_TIME (SYS_START, SYS_END);


GO
ALTER TABLE T SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE=T_HST));


GO
ALTER TABLE T SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE=T_HST, DATA_CONSISTENCY_CHECK=ON));


GO
ALTER TABLE T SET (SYSTEM_VERSIONING = ON);


GO
ALTER TABLE T SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE=T_HST, DATA_CONSISTENCY_CHECK=OFF));


GO
ALTER TABLE T
    ADD SYS_START DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
        SYS_END   DATETIME2 (7) GENERATED ALWAYS AS ROW END   NOT NULL, 
        PERIOD FOR SYSTEM_TIME (SYS_START, SYS_END);


GO
ALTER TABLE T DROP PERIOD FOR SYSTEM_TIME;


GO
ALTER TABLE T
    ADD COL_A DATETIME2 (7),
        COL_B DATETIME2 (7),
        COL_C INT          , 
        PERIOD FOR SYSTEM_TIME (SYS_START, SYS_END);


GO
ALTER TABLE T
    ADD COL_USER_ID_START VARBINARY (85) GENERATED ALWAYS AS SUSER_SID START NOT NULL;


GO
ALTER TABLE T
    ADD COL_USER_ID_START VARBINARY (85) GENERATED ALWAYS AS SUSER_SID START;


GO
ALTER TABLE T
    ADD COL_USER_ID_END VARBINARY (85) GENERATED ALWAYS AS SUSER_SID END NOT NULL;


GO
ALTER TABLE T
    ADD COL_USER_NAME_START NVARCHAR (128) GENERATED ALWAYS AS SUSER_SNAME START NOT NULL;


GO
ALTER TABLE T
    ADD COL_USER_NAME_END NVARCHAR (128) GENERATED ALWAYS AS SUSER_SNAME END NOT NULL;


GO
ALTER TABLE T
    ADD COL_USER_ID_START   VARBINARY (85) GENERATED ALWAYS AS SUSER_SID START   NOT NULL,
        COL_USER_ID_END     VARBINARY (85) GENERATED ALWAYS AS SUSER_SID END     NOT NULL,
        COL_USER_NAME_START NVARCHAR (128) GENERATED ALWAYS AS SUSER_SNAME START NOT NULL,
        COL_USER_NAME_END   NVARCHAR (128) GENERATED ALWAYS AS SUSER_SNAME END   NOT NULL;


GO
ALTER TABLE T
    ADD COL_USER_ID_START   VARBINARY (85) GENERATED ALWAYS AS SUSER_SID START  ,
        COL_USER_ID_END     VARBINARY (85) GENERATED ALWAYS AS SUSER_SID END    ,
        COL_USER_NAME_START NVARCHAR (128) GENERATED ALWAYS AS SUSER_SNAME START,
        COL_USER_NAME_END   NVARCHAR (128) GENERATED ALWAYS AS SUSER_SNAME END  ;


GO
ALTER TABLE T
    ADD COL_USER_ID_START   VARBINARY (85) GENERATED ALWAYS AS SUSER_SID START HIDDEN   NOT NULL,
        COL_USER_ID_END     VARBINARY (85) GENERATED ALWAYS AS SUSER_SID END HIDDEN     NOT NULL,
        COL_USER_NAME_START NVARCHAR (128) GENERATED ALWAYS AS SUSER_SNAME START HIDDEN NOT NULL,
        COL_USER_NAME_END   NVARCHAR (128) GENERATED ALWAYS AS SUSER_SNAME END HIDDEN   NOT NULL;


GO
ALTER TABLE T
    ADD COL_USER_ID_START   VARBINARY (85) GENERATED ALWAYS AS SUSER_SID START   NOT NULL,
        COL_USER_ID_END     VARBINARY (85) GENERATED ALWAYS AS SUSER_SID END     NOT NULL,
        COL_USER_NAME_START NVARCHAR (128) GENERATED ALWAYS AS SUSER_SNAME START NOT NULL,
        COL_USER_NAME_END   NVARCHAR (128) GENERATED ALWAYS AS SUSER_SNAME END   NOT NULL,
        SYS_START           DATETIME2 (7) GENERATED ALWAYS AS ROW START          NOT NULL,
        SYS_END             DATETIME2 (7) GENERATED ALWAYS AS ROW END            NOT NULL, 
        PERIOD FOR SYSTEM_TIME (SYS_START, SYS_END);


GO
ALTER TABLE T
    ADD COL_USER_ID_START   VARBINARY (85) GENERATED ALWAYS AS SUSER_SID START   NOT NULL,
        COL_USER_ID_END     VARBINARY (85) GENERATED ALWAYS AS SUSER_SID END     NOT NULL,
        COL_USER_NAME_START NVARCHAR (128) GENERATED ALWAYS AS SUSER_SNAME START NOT NULL,
        COL_USER_NAME_END   NVARCHAR (128) GENERATED ALWAYS AS SUSER_SNAME END   NOT NULL, 
        PERIOD FOR SYSTEM_TIME (SYS_START, SYS_END);


GO
ALTER TABLE T MERGE RANGE ('2004-01-01');


GO
ALTER TABLE T SPLIT RANGE ('2004-01-01');


GO
ALTER TABLE T SPLIT RANGE (10);


GO
ALTER TABLE T MERGE RANGE (10);


GO
ALTER TABLE T MERGE RANGE (NULL);


