CREATE NONCLUSTERED COLUMNSTORE INDEX NCCI
    ON T(A) WHERE A > 0;

CREATE NONCLUSTERED COLUMNSTORE INDEX NCCI
    ON T(A) WHERE A > 0 WITH (COMPRESSION_DELAY = 42);

CREATE CLUSTERED COLUMNSTORE INDEX CCI
    ON t WITH (ORDER (A));

CREATE CLUSTERED COLUMNSTORE INDEX CCI
    ON t WITH (SORT_IN_TEMPDB = ON, ORDER (A, B));
