CREATE TABLE t (
    c VARCHAR (100) SPARSE MASKED WITH (FUNCTION = 'default()') NULL
);

CREATE TABLE t (
    c VARCHAR (100) SPARSE MASKED WITH (FUNCTION = 'default()') NULL
);

CREATE TABLE t (
    c VARBINARY (MAX) SPARSE FILESTREAM MASKED WITH (FUNCTION = 'default()') NULL
);
