CREATE TABLE T (
    i INT NOT NULL INDEX ix_i UNIQUE NONCLUSTERED HASH WITH (BUCKET_COUNT = 10000),
    k INT NOT NULL
)
WITH (MEMORY_OPTIMIZED = ON, DURABILITY = SCHEMA_ONLY);


GO
CREATE TYPE TT AS TABLE (
    i INT NOT NULL INDEX ix_i UNIQUE NONCLUSTERED,
    k INT NOT NULL)
    WITH (MEMORY_OPTIMIZED = ON);


GO
CREATE TABLE T (
    i INT NOT NULL INDEX ix_i UNIQUE NONCLUSTERED HASH (i, k) WITH (BUCKET_COUNT = 10000),
    k INT NOT NULL
)
WITH (MEMORY_OPTIMIZED = OFF, DURABILITY = SCHEMA_ONLY);


GO
CREATE TYPE TT AS TABLE (
    i INT NOT NULL INDEX ix_i UNIQUE,
    k INT NOT NULL)
    WITH (MEMORY_OPTIMIZED = ON);


GO
CREATE TABLE T (
    i INT NOT NULL,
    k INT NOT NULL,
    INDEX ix_i UNIQUE NONCLUSTERED HASH (i, k) WITH (BUCKET_COUNT = 10000)
)
WITH (MEMORY_OPTIMIZED = OFF, DURABILITY = SCHEMA_ONLY);


GO
ALTER TABLE t1
    ADD INDEX i1 UNIQUE NONCLUSTERED HASH (c1) WITH (BUCKET_COUNT = 256);

ALTER TABLE t1
    ADD INDEX i1 UNIQUE NONCLUSTERED (c1, c2);