//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.TransactSql.ScriptDom {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlScriptGeneratorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlScriptGeneratorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SqlServer.TransactSql.ScriptDom.SqlScriptGeneratorResource", typeof(SqlScriptGeneratorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular alignment points are found.
        /// </summary>
        internal static string CircularAlignmentPoints {
            get {
                return ResourceManager.GetString("CircularAlignmentPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid alignment operation.
        /// </summary>
        internal static string InvalidAlignmentOperation {
            get {
                return ResourceManager.GetString("InvalidAlignmentOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-Sql Script Generator only supports generating source for T-Sql Script DOM Trees.
        /// </summary>
        internal static string ScriptDomTreeTypeNotSupported {
            get {
                return ResourceManager.GetString("ScriptDomTreeTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokenization Failed.
        /// </summary>
        internal static string TokenizationFailed {
            get {
                return ResourceManager.GetString("TokenizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified token type does not have a string representation: {0}.
        /// </summary>
        internal static string TokenTypeDoesNotHaveStringRepresentation {
            get {
                return ResourceManager.GetString("TokenTypeDoesNotHaveStringRepresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled option is encountered.
        /// </summary>
        internal static string UnhandledOption {
            get {
                return ResourceManager.GetString("UnhandledOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value ({0}) provided for type ({1}) is unknown.
        /// </summary>
        internal static string UnknownEnumValue {
            get {
                return ResourceManager.GetString("UnknownEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown literal type is encountered.
        /// </summary>
        internal static string UnknownLiteralType {
            get {
                return ResourceManager.GetString("UnknownLiteralType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown quote type is encountered.
        /// </summary>
        internal static string UnknownQuoteType {
            get {
                return ResourceManager.GetString("UnknownQuoteType", resourceCulture);
            }
        }
    }
}
