//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.TransactSql.ScriptDom {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TSqlParserResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TSqlParserResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SqlServer.TransactSql.ScriptDom.TSqlParserResource", typeof(TSqlParserResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal parser error occurred..
        /// </summary>
        internal static string SQL46001Message {
            get {
                return ResourceManager.GetString("SQL46001Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} data type cannot have both National and Varying keywords..
        /// </summary>
        internal static string SQL46002Message {
            get {
                return ResourceManager.GetString("SQL46002Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} data type cannot have the National keyword..
        /// </summary>
        internal static string SQL46003Message {
            get {
                return ResourceManager.GetString("SQL46003Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} data type cannot have the Varying keyword..
        /// </summary>
        internal static string SQL46004Message {
            get {
                return ResourceManager.GetString("SQL46004Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0} but encountered {1} instead..
        /// </summary>
        internal static string SQL46005Message {
            get {
                return ResourceManager.GetString("SQL46005Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a WITH option for a procedure..
        /// </summary>
        internal static string SQL46006Message {
            get {
                return ResourceManager.GetString("SQL46006Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a WITH option for a trigger..
        /// </summary>
        internal static string SQL46007Message {
            get {
                return ResourceManager.GetString("SQL46007Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} data type cannot have exactly one parameter..
        /// </summary>
        internal static string SQL46008Message {
            get {
                return ResourceManager.GetString("SQL46008Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} data type cannot have two parameters..
        /// </summary>
        internal static string SQL46009Message {
            get {
                return ResourceManager.GetString("SQL46009Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect syntax near {0}..
        /// </summary>
        internal static string SQL46010Message {
            get {
                return ResourceManager.GetString("SQL46010Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Unique or Primary Key constraints can be created on computed columns, while Check, Foreign Key, and Not Null constraints require that computed columns be persisted..
        /// </summary>
        internal static string SQL46011Message {
            get {
                return ResourceManager.GetString("SQL46011Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one Default constraint is defined..
        /// </summary>
        internal static string SQL46012Message {
            get {
                return ResourceManager.GetString("SQL46012Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH VALUES can only be defined in an ALTER TABLE statement for a Default constraint..
        /// </summary>
        internal static string SQL46013Message {
            get {
                return ResourceManager.GetString("SQL46013Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Default constraint can exist only at the column level in a CREATE or ALTER TABLE statement..
        /// </summary>
        internal static string SQL46014Message {
            get {
                return ResourceManager.GetString("SQL46014Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid option for an index that has the backward compatible syntax..
        /// </summary>
        internal static string SQL46015Message {
            get {
                return ResourceManager.GetString("SQL46015Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column name is not valid. No table name was specified..
        /// </summary>
        internal static string SQL46016Message {
            get {
                return ResourceManager.GetString("SQL46016Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of column names cannot exceed 1024..
        /// </summary>
        internal static string SQL46017Message {
            get {
                return ResourceManager.GetString("SQL46017Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid option for CREATE STATISTICS..
        /// </summary>
        internal static string SQL46018Message {
            get {
                return ResourceManager.GetString("SQL46018Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid option for SAMPLE..
        /// </summary>
        internal static string SQL46019Message {
            get {
                return ResourceManager.GetString("SQL46019Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid option for UPDATE STATISTICS..
        /// </summary>
        internal static string SQL46020Message {
            get {
                return ResourceManager.GetString("SQL46020Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not allow a database name to be specified..
        /// </summary>
        internal static string SQL46021Message {
            get {
                return ResourceManager.GetString("SQL46021Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a recognized table or a view hint..
        /// </summary>
        internal static string SQL46022Message {
            get {
                return ResourceManager.GetString("SQL46022Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a recognized GROUP BY option..
        /// </summary>
        internal static string SQL46023Message {
            get {
                return ResourceManager.GetString("SQL46023Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a recognized COMPUTE function..
        /// </summary>
        internal static string SQL46024Message {
            get {
                return ResourceManager.GetString("SQL46024Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a WITH option for a view..
        /// </summary>
        internal static string SQL46025Message {
            get {
                return ResourceManager.GetString("SQL46025Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a WITH option for a CREATE FUNCTION or ALTER FUNCTION statement..
        /// </summary>
        internal static string SQL46026Message {
            get {
                return ResourceManager.GetString("SQL46026Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exactly two part names are required in a DROP INDEX statement..
        /// </summary>
        internal static string SQL46027Message {
            get {
                return ResourceManager.GetString("SQL46027Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more than four parts can be specified for this element name..
        /// </summary>
        internal static string SQL46028Message {
            get {
                return ResourceManager.GetString("SQL46028Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file occurred..
        /// </summary>
        internal static string SQL46029Message {
            get {
                return ResourceManager.GetString("SQL46029Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected but did not find a closing quotation mark after the character string {0}..
        /// </summary>
        internal static string SQL46030Message {
            get {
                return ResourceManager.GetString("SQL46030Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected but did not find a closing square bracket after the identifier {0}..
        /// </summary>
        internal static string SQL46031Message {
            get {
                return ResourceManager.GetString("SQL46031Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected but did not find an end comment mark &apos;*/&apos;..
        /// </summary>
        internal static string SQL46032Message {
            get {
                return ResourceManager.GetString("SQL46032Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected but did not find a closing parenthesis after the identifier {0}..
        /// </summary>
        internal static string SQL46033Message {
            get {
                return ResourceManager.GetString("SQL46033Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one EXECUTE AS clause is allowed in this statement..
        /// </summary>
        internal static string SQL46034Message {
            get {
                return ResourceManager.GetString("SQL46034Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An ODBC join clause must encapsulate a qualified join or another ODBC join clause..
        /// </summary>
        internal static string SQL46035Message {
            get {
                return ResourceManager.GetString("SQL46035Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This usage of an ODBC clause is not supported. You must use curly brackets as delimiters..
        /// </summary>
        internal static string SQL46036Message {
            get {
                return ResourceManager.GetString("SQL46036Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The script contains syntax that is not supported by the version of SQL Server that is associated with the database project..
        /// </summary>
        internal static string SQL46037Message {
            get {
                return ResourceManager.GetString("SQL46037Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For DROP STATISTICS, you must provide both the object (table or view) name and the statistics name, in the form &quot;objectName.statisticsName&quot;..
        /// </summary>
        internal static string SQL46038Message {
            get {
                return ResourceManager.GetString("SQL46038Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot use the OUTPUT option in a CREATE FUNCTION statement..
        /// </summary>
        internal static string SQL46039Message {
            get {
                return ResourceManager.GetString("SQL46039Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An action of type &apos;INSERT&apos; is not allowed in &apos;WHEN SOURCE NOT MATCHED&apos; or &apos;MATCHED&apos; clauses of a MERGE statement..
        /// </summary>
        internal static string SQL46040Message {
            get {
                return ResourceManager.GetString("SQL46040Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An action of type &apos;{0}&apos; is not allowed in the &apos;WHEN NOT MATCHED&apos; clause of a MERGE statement..
        /// </summary>
        internal static string SQL46041Message {
            get {
                return ResourceManager.GetString("SQL46041Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one column ROWGUIDCOL constraint is specified..
        /// </summary>
        internal static string SQL46042Message {
            get {
                return ResourceManager.GetString("SQL46042Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one column IDENTITY constraint is specified..
        /// </summary>
        internal static string SQL46043Message {
            get {
                return ResourceManager.GetString("SQL46043Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have a logon trigger with a scope that is anything other than &apos;ALL SERVER&apos;..
        /// </summary>
        internal static string SQL46044Message {
            get {
                return ResourceManager.GetString("SQL46044Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The integer value {0} is out of range..
        /// </summary>
        internal static string SQL46045Message {
            get {
                return ResourceManager.GetString("SQL46045Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ORDER BY clause is not valid in views, inline functions, derived tables, sub-queries, and common table expressions, unless TOP or FOR XML or OFFSET is also specified..
        /// </summary>
        internal static string SQL46047Message {
            get {
                return ResourceManager.GetString("SQL46047Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TOP N WITH TIES clause is not allowed without a corresponding ORDER BY clause..
        /// </summary>
        internal static string SQL46048Message {
            get {
                return ResourceManager.GetString("SQL46048Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option {0} is specified more than once..
        /// </summary>
        internal static string SQL46049Message {
            get {
                return ResourceManager.GetString("SQL46049Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ALTER DATABASE change tracking option &apos;{0}&apos; was specified more than once. Each option can be specified only once..
        /// </summary>
        internal static string SQL46050Message {
            get {
                return ResourceManager.GetString("SQL46050Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILESTREAM can only be declared for VARBINARY(MAX) columns..
        /// </summary>
        internal static string SQL46051Message {
            get {
                return ResourceManager.GetString("SQL46051Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following string is not defined as a language alias in syslanguages: {0}.
        /// </summary>
        internal static string SQL46052Message {
            get {
                return ResourceManager.GetString("SQL46052Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified locale ID is not valid. Verify that the locale ID is correct and that a corresponding language resource has been installed..
        /// </summary>
        internal static string SQL46053Message {
            get {
                return ResourceManager.GetString("SQL46053Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified maximum size limit is greater than the maximum value allowed. The maximum size limit must be less than 16777215 TB..
        /// </summary>
        internal static string SQL46054Message {
            get {
                return ResourceManager.GetString("SQL46054Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion failed when converting from a character string to uniqueidentifier..
        /// </summary>
        internal static string SQL46055Message {
            get {
                return ResourceManager.GetString("SQL46055Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FILEPATH option must be specified for FILE audit target in a CREATE SERVER AUDIT statement..
        /// </summary>
        internal static string SQL46056Message {
            get {
                return ResourceManager.GetString("SQL46056Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; is not a valid index option in &apos;{1}&apos; statement..
        /// </summary>
        internal static string SQL46057Message {
            get {
                return ResourceManager.GetString("SQL46057Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same large data placement option &apos;{0}&apos; has been specified twice..
        /// </summary>
        internal static string SQL46058Message {
            get {
                return ResourceManager.GetString("SQL46058Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an incorrect expression in the WHERE clause..
        /// </summary>
        internal static string SQL46059Message {
            get {
                return ResourceManager.GetString("SQL46059Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill factor {0} is not a valid percentage; fill factor must be between 1 and 100..
        /// </summary>
        internal static string SQL46060Message {
            get {
                return ResourceManager.GetString("SQL46060Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In an ALTER TABLE REBUILD or ALTER INDEX REBUILD statement, when a partition is specified in a DATA_COMPRESSION or XML_COMPRESSION clause, same PARTITION must be specified..
        /// </summary>
        internal static string SQL46061Message {
            get {
                return ResourceManager.GetString("SQL46061Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NEWNAME option is allowed only with ALTER DATABASE MODIFY FILE syntax..
        /// </summary>
        internal static string SQL46062Message {
            get {
                return ResourceManager.GetString("SQL46062Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty string is not allowed here..
        /// </summary>
        internal static string SQL46063Message {
            get {
                return ResourceManager.GetString("SQL46063Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file option FILENAME is required in this CREATE/ALTER DATABASE statement..
        /// </summary>
        internal static string SQL46065Message {
            get {
                return ResourceManager.GetString("SQL46065Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the {0} option, four parameters must be specified..
        /// </summary>
        internal static string SQL46066Message {
            get {
                return ResourceManager.GetString("SQL46066Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bounding-box coordinates apply only within a USING GEOMETRY_GRID clause..
        /// </summary>
        internal static string SQL46067Message {
            get {
                return ResourceManager.GetString("SQL46067Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All three options (PROCEDURE_NAME, EXECUTE AS, MAX_QUEUE_READERS) must be specified..
        /// </summary>
        internal static string SQL46069Message {
            get {
                return ResourceManager.GetString("SQL46069Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The use of the option {0} in the DROP INDEX statement is not valid..
        /// </summary>
        internal static string SQL46070Message {
            get {
                return ResourceManager.GetString("SQL46070Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting CREATE/UPDATE STATISTICS options &quot;SAMPLE&quot; and &quot;FULLSCAN&quot;.
        /// </summary>
        internal static string SQL46071Message {
            get {
                return ResourceManager.GetString("SQL46071Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CHANGE_TRACKING_CONTEXT WITH clause cannot be used with a SELECT statement..
        /// </summary>
        internal static string SQL46072Message {
            get {
                return ResourceManager.GetString("SQL46072Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for the CELLS_PER_OBJECT spatial index option should be between 1 and 8192..
        /// </summary>
        internal static string SQL46073Message {
            get {
                return ResourceManager.GetString("SQL46073Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index hints are only allowed in a FROM or OPTION clause..
        /// </summary>
        internal static string SQL46074Message {
            get {
                return ResourceManager.GetString("SQL46074Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nested INSERT, UPDATE, DELETE, or MERGE statement is not allowed inside another nested INSERT, UPDATE, DELETE, or MERGE statement..
        /// </summary>
        internal static string SQL46075Message {
            get {
                return ResourceManager.GetString("SQL46075Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nested INSERT, UPDATE, DELETE, or MERGE statement is not allowed in a SELECT statement that is not the immediate source of rows for an INSERT statement..
        /// </summary>
        internal static string SQL46076Message {
            get {
                return ResourceManager.GetString("SQL46076Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nested INSERT, UPDATE, DELETE, or MERGE statement is not allowed in the FROM clause of an UPDATE or DELETE statement..
        /// </summary>
        internal static string SQL46077Message {
            get {
                return ResourceManager.GetString("SQL46077Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nested INSERT, UPDATE, DELETE, or MERGE statement is not allowed in the USING clause of a MERGE statement..
        /// </summary>
        internal static string SQL46078Message {
            get {
                return ResourceManager.GetString("SQL46078Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nested INSERT, UPDATE, DELETE, or MERGE statement must have an OUTPUT clause..
        /// </summary>
        internal static string SQL46079Message {
            get {
                return ResourceManager.GetString("SQL46079Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required parameter ROLE was not specified..
        /// </summary>
        internal static string SQL46080Message {
            get {
                return ResourceManager.GetString("SQL46080Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index option {0} in the CREATE SPATIAL INDEX statement must appear before the general index options..
        /// </summary>
        internal static string SQL46081Message {
            get {
                return ResourceManager.GetString("SQL46081Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either a format file or one of the three options (SINGLE_BLOB, SINGLE_CLOB, or SINGLE_NCLOB) must be specified..
        /// </summary>
        internal static string SQL46082Message {
            get {
                return ResourceManager.GetString("SQL46082Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WHERE CURRENT OF clause is not allowed in a nested INSERT, UPDATE, DELETE, or MERGE statement..
        /// </summary>
        internal static string SQL46083Message {
            get {
                return ResourceManager.GetString("SQL46083Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CUBE, ROLLUP, and GROUPING SETS constructs are not allowed in a GROUP BY ALL clause..
        /// </summary>
        internal static string SQL46084Message {
            get {
                return ResourceManager.GetString("SQL46084Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WITH CUBE and WITH ROLLUP options are not permitted with a ROLLUP, CUBE, or GROUPING SETS specification..
        /// </summary>
        internal static string SQL46085Message {
            get {
                return ResourceManager.GetString("SQL46085Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISTINCT is not allowed for windowed aggregate functions..
        /// </summary>
        internal static string SQL46086Message {
            get {
                return ResourceManager.GetString("SQL46086Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The integer value {0} for &quot;LISTENER_PORT&quot; is out of range. The value should be between 1024 and 32767..
        /// </summary>
        internal static string SQL46087Message {
            get {
                return ResourceManager.GetString("SQL46087Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use the OUTPUT option when passing a constant to a stored procedure..
        /// </summary>
        internal static string SQL46088Message {
            get {
                return ResourceManager.GetString("SQL46088Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must pass parameter number {0} and subsequent parameters as &apos;@name = value&apos;. After the form &apos;@name = value&apos; has been used, all subsequent parameters must be passed in the form &apos;@name = value&apos;..
        /// </summary>
        internal static string SQL46089Message {
            get {
                return ResourceManager.GetString("SQL46089Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error: Duplicate specification of the action &quot;{0}&quot; in the trigger declaration.
        /// </summary>
        internal static string SQL46090Message {
            get {
                return ResourceManager.GetString("SQL46090Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} for index option &apos;maxdop&apos; is out of range. It should be between 0 and 32767..
        /// </summary>
        internal static string SQL46091Message {
            get {
                return ResourceManager.GetString("SQL46091Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;: Temporary views are not allowed..
        /// </summary>
        internal static string SQL46092Message {
            get {
                return ResourceManager.GetString("SQL46092Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;: Temporary functions are not allowed..
        /// </summary>
        internal static string SQL46093Message {
            get {
                return ResourceManager.GetString("SQL46093Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent values must be between 0 and 100..
        /// </summary>
        internal static string SQL46094Message {
            get {
                return ResourceManager.GetString("SQL46094Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Identifier that starts with &apos;{0}&apos; is too long.  Maximum length is 128..
        /// </summary>
        internal static string SQL46095Message {
            get {
                return ResourceManager.GetString("SQL46095Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} cannot be provided for users that cannot authenticate in a database..
        /// </summary>
        internal static string SQL46096Message {
            get {
                return ResourceManager.GetString("SQL46096Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} statement must be terminated by a semi-colon (;).
        /// </summary>
        internal static string SQL46097Message {
            get {
                return ResourceManager.GetString("SQL46097Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subqueries are not allowed in this context. Only scalar expressions are allowed..
        /// </summary>
        internal static string SQL46098Message {
            get {
                return ResourceManager.GetString("SQL46098Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RANGE in OVER clause is only supported with UNBOUNDED and CURRENT ROW frame delimiters..
        /// </summary>
        internal static string SQL46099Message {
            get {
                return ResourceManager.GetString("SQL46099Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVER clause has illegal window frame specification..
        /// </summary>
        internal static string SQL46100Message {
            get {
                return ResourceManager.GetString("SQL46100Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time value {0} for MAX_DURATION is out of range. It should be between 0 and 71582..
        /// </summary>
        internal static string SQL46101Message {
            get {
                return ResourceManager.GetString("SQL46101Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time value {0} for MAX_DURATION is not allowed for ABORT_AFTER_WAIT = {1}..
        /// </summary>
        internal static string SQL46102Message {
            get {
                return ResourceManager.GetString("SQL46102Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporal tables require the lower boundary column name in SYSTEM_TIME PERIOD definition to match the GENERATED ALWAYS AS ROW START column name..
        /// </summary>
        internal static string SQL46103Message {
            get {
                return ResourceManager.GetString("SQL46103Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporal tables require the upper boundary column name in SYSTEM_TIME PERIOD definition to match the GENERATED ALWAYS AS ROW END column name..
        /// </summary>
        internal static string SQL46104Message {
            get {
                return ResourceManager.GetString("SQL46104Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERATED ALWAYS AS ROW START column must be defined for Temporal tables..
        /// </summary>
        internal static string SQL46105Message {
            get {
                return ResourceManager.GetString("SQL46105Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERATED ALWAYS AS ROW END column must be defined for Temporal tables..
        /// </summary>
        internal static string SQL46106Message {
            get {
                return ResourceManager.GetString("SQL46106Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered indexes are not supported on memory optimized tables..
        /// </summary>
        internal static string SQL46107Message {
            get {
                return ResourceManager.GetString("SQL46107Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nonclustered column store indexes are not supported on memory optimized tables..
        /// </summary>
        internal static string SQL46108Message {
            get {
                return ResourceManager.GetString("SQL46108Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERATED ALWAYS AS USER ID START column must be unique..
        /// </summary>
        internal static string SQL46109Message {
            get {
                return ResourceManager.GetString("SQL46109Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERATED ALWAYS AS USER ID END column must be unique..
        /// </summary>
        internal static string SQL46110Message {
            get {
                return ResourceManager.GetString("SQL46110Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERATED ALWAYS AS USER NAME START column must be unique..
        /// </summary>
        internal static string SQL46111Message {
            get {
                return ResourceManager.GetString("SQL46111Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERATED ALWAYS AS USER NAME END column must be unique..
        /// </summary>
        internal static string SQL46112Message {
            get {
                return ResourceManager.GetString("SQL46112Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create GENERATED ALWAYS column when SYSTEM_TIME period is not defined.
        /// </summary>
        internal static string SQL46113Message {
            get {
                return ResourceManager.GetString("SQL46113Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified COMPRESSION_DELAY option value {0} is invalid. The valid range for disk-based table is AUTO or between (0, 10080) minutes and for memory-optimized table is AUTO, 0 or between (60, 10080) minutes..
        /// </summary>
        internal static string SQL46114Message {
            get {
                return ResourceManager.GetString("SQL46114Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set configuration option to PRIMARY when FOR SECONDARY is not specified..
        /// </summary>
        internal static string SQL46115Message {
            get {
                return ResourceManager.GetString("SQL46115Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid value for system versioning history retention period. The value must be a positive number larger than 0..
        /// </summary>
        internal static string SQL46116Message {
            get {
                return ResourceManager.GetString("SQL46116Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The script contains clause {0} which is not supported by the targeted version of SQL Server..
        /// </summary>
        internal static string SQL46117Message {
            get {
                return ResourceManager.GetString("SQL46117Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV format option is supported for char and widechar datafiletype options..
        /// </summary>
        internal static string SQL46118Message {
            get {
                return ResourceManager.GetString("SQL46118Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format option cannot be specified together with SINGLE_BLOB, SINGLE_CLOB or SINGLE_NCLOB option..
        /// </summary>
        internal static string SQL46119Message {
            get {
                return ResourceManager.GetString("SQL46119Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} option is not supported for this type of login..
        /// </summary>
        internal static string SQL46120Message {
            get {
                return ResourceManager.GetString("SQL46120Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SID and type options are both required for this type of login..
        /// </summary>
        internal static string SQL46121Message {
            get {
                return ResourceManager.GetString("SQL46121Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RANK value cannot be provided as text.
        /// </summary>
        internal static string SQL46122Message {
            get {
                return ResourceManager.GetString("SQL46122Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} value must be provided as text.
        /// </summary>
        internal static string SQL46123Message {
            get {
                return ResourceManager.GetString("SQL46123Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal sensitivity rank value provided.
        /// </summary>
        internal static string SQL46124Message {
            get {
                return ResourceManager.GetString("SQL46124Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal sensitivity option {0} recognized. Legal options are: LABEL, LABEL_ID, INFORMATION_TYPE, INFORMATION_TYPE_ID, RANK.
        /// </summary>
        internal static string SQL46125Message {
            get {
                return ResourceManager.GetString("SQL46125Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PATH option must be specified for URL audit target in a CREATE SERVER AUDIT statement..
        /// </summary>
        internal static string SQL46126Message {
            get {
                return ResourceManager.GetString("SQL46126Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CTAS statement requires a distribution option..
        /// </summary>
        internal static string SQL46127Message {
            get {
                return ResourceManager.GetString("SQL46127Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REJECTED_ROW_LOCATION cannot be specified in a CREATE EXTERNAL TABLE AS SELECT statement..
        /// </summary>
        internal static string SQL46128Message {
            get {
                return ResourceManager.GetString("SQL46128Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GROUP BY clause can only contain a single DISTRIBUTED_AGG query hint..
        /// </summary>
        internal static string SQL46129Message {
            get {
                return ResourceManager.GetString("SQL46129Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COPY statement failed because the value for option {0} is invalid..
        /// </summary>
        internal static string SQL46130Message {
            get {
                return ResourceManager.GetString("SQL46130Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COPY statement failed because {0} contains invalid number of characters..
        /// </summary>
        internal static string SQL46131Message {
            get {
                return ResourceManager.GetString("SQL46131Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Command SAS Key is invalid.
        /// </summary>
        internal static string SQL46132Message {
            get {
                return ResourceManager.GetString("SQL46132Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a multiple of 0.25..
        /// </summary>
        internal static string SQL46133Message {
            get {
                return ResourceManager.GetString("SQL46133Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time input should be in HH:MM format.
        /// </summary>
        internal static string SQL46134Message {
            get {
                return ResourceManager.GetString("SQL46134Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILTER_COLUMN is {0}.
        /// </summary>
        internal static string SQL46135Message {
            get {
                return ResourceManager.GetString("SQL46135Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERATED ALWAYS AS TRANSACTION ID START column must be unique..
        /// </summary>
        internal static string SQL46136Message {
            get {
                return ResourceManager.GetString("SQL46136Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERATED ALWAYS AS TRANSACTION ID END column must be unique..
        /// </summary>
        internal static string SQL46137Message {
            get {
                return ResourceManager.GetString("SQL46137Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERATED ALWAYS AS SEQUENCE NUMBER START column must be unique..
        /// </summary>
        internal static string SQL46138Message {
            get {
                return ResourceManager.GetString("SQL46138Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERATED ALWAYS AS SEQUENCE NUMBER END column must be unique..
        /// </summary>
        internal static string SQL46139Message {
            get {
                return ResourceManager.GetString("SQL46139Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ledger tables are not supported in the targeted version..
        /// </summary>
        internal static string SQL46140Message {
            get {
                return ResourceManager.GetString("SQL46140Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ledger tables are not supported in the targeted version..
        /// </summary>
        internal static string SQL46141Message {
            get {
                return ResourceManager.GetString("SQL46141Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the provided options cannot be used with PARQUET format..
        /// </summary>
        internal static string SQL46142Message {
            get {
                return ResourceManager.GetString("SQL46142Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREDENTIAL and SERVER_CREDENTIAL parameters cannot be specified at the same time..
        /// </summary>
        internal static string SQL46143Message {
            get {
                return ResourceManager.GetString("SQL46143Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required parameter {0} must be provided..
        /// </summary>
        internal static string SQL46144Message {
            get {
                return ResourceManager.GetString("SQL46144Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-defined.
        /// </summary>
        internal static string UserDefined {
            get {
                return ResourceManager.GetString("UserDefined", resourceCulture);
            }
        }
    }
}
