BULK INSERT t1 FROM 'f1'
    WITH (FORMAT = 'CSV', ESCAPECHAR = '\\');

BULK INSERT t1 FROM 'f1'
    WITH (FORMAT = 'CSV', ESCAPECHAR = N'#', CODEPAGE = 'RAW');

BULK INSERT t1 FROM 'f1'
    WITH (FORMAT = 'CSV', ESCAPECHAR = '\\', FIELDQUOTE = '#', CODEPAGE = 'RAW');

BULK INSERT t1 FROM 'f1'
    WITH (FORMAT = 'CSV', ESCAPECHAR = '\\', FORMATFILE = 'ff1', ORDER (c1), ERRORFILE = 'ef1');

BULK INSERT t1 FROM 'f1'
    WITH (FORMAT = 'CSV', ESCAPECHAR = '\\', FIELDTERMINATOR = ',', ROWTERMINATOR = '\r\n', DATAFILETYPE = 'widechar');

BULK INSERT t1 FROM 'f1'
    WITH (FORMAT = 'CSV', ESCAPECHAR = '\\', FIRSTROW = 5, LASTROW = 10, MAXERRORS = 0, ROWS_PER_BATCH = 1, FIRE_TRIGGERS, KEEPNULLS);

