SELECT *
FROM OPENROWSET (BULK 'f1', FORMATFILE = 'ff1', FORMAT = 'CSV', ESCAPECHAR = N'\\', FIELDQUOTE = '"') AS a;

SELECT *
FROM OPENROWSET (BULK 'f1', FORMATFILE = 'ff1', FORMAT = 'CSV', ESCAPECHAR = '\\', CODEPAGE = 'RAW') AS a;

SELECT *
FROM OPENROWSET (BULK 'f1', FORMATFILE = 'ff1', FORMAT = 'CSV', ESCAPECHAR = '\\', ORDER (c1), ERRORFILE = 'ef1') AS a;

SELECT *
FROM OPENROWSET (BULK 'f1', FORMATFILE = 'ff1', FORMAT = 'CSV', ESCAPECHAR = '\\', FIRSTROW = 5, LASTROW = 10, MAXERRORS = 0, ROWS_PER_BATCH = 1) AS a;

SELECT *
FROM OPENROWSET (BULK 'f1', ESCAPECHAR = '\\', FORMAT = 'csV', FORMATFILE = 'ff1') AS a;

SELECT *
FROM OPENROWSET (BULK 'f1', FORMAT = 'PARQUET') AS a;

SELECT *
FROM OPENROWSET (BULK 'f1', FORMAT = 'DELTA') AS a;

SELECT *
FROM OPENROWSET (BULK 'f1', FORMAT = 'PARQUET', FIELDTERMINATOR = 'aa', ROWTERMINATOR = 'bb', ESCAPECHAR = 'd', FIRSTROW = 1, FIELDQUOTE = 'e', DATA_COMPRESSION = 'gzip', HEADER_ROW = TRUE, DATAFILETYPE = 'widechar', CODEPAGE = 'ACP') AS a;

SELECT *
FROM OPENROWSET (BULK 'f1', FORMAT = 'CSV', FIELDTERMINATOR = 'aa', ROWTERMINATOR = 'bb', ESCAPECHAR = 'd', FIRSTROW = 1, FIELDQUOTE = 'e', DATA_COMPRESSION = 'gzip', PARSER_VERSION = '1.0', HEADER_ROW = TRUE, DATAFILETYPE = 'widechar', CODEPAGE = 'ACP', ROWSET_OPTIONS = '{"READ_OPTIONS":["ALLOW_INCONSISTENT_READS"]}') WITH ([region] VARCHAR (100)) AS a;

SELECT *
FROM OPENROWSET (BULK 'f1', FORMAT = 'CSV') WITH ([region] VARCHAR (100) 1, [continent] VARCHAR (100) COLLATE latin1_general_bin2 2, [products] VARCHAR (100) 3, [status] INT 4) AS a;

SELECT *
FROM OPENROWSET (BULK 'f1', FORMAT = 'CSV', FIELDTERMINATOR = 'aa', ROWTERMINATOR = 'bb', ESCAPECHAR = 'd', FIRSTROW = 1, FIELDQUOTE = 'e', DATA_COMPRESSION = 'gzip', PARSER_VERSION = '1.0', HEADER_ROW = TRUE, DATAFILETYPE = 'widechar', CODEPAGE = 'ACP', ROWSET_OPTIONS = '{"READ_OPTIONS":["ALLOW_INCONSISTENT_READS"]}') WITH ([region] VARCHAR (100)) AS a;

SELECT *
FROM OPENROWSET (BULK 'f2', FORMAT = 'CSV', FIELDTERMINATOR = 'x', ROWTERMINATOR = 'y', ESCAPECHAR = 'z', FIRSTROW = 1, FIELDQUOTE = 'e', DATA_COMPRESSION = 'gzip', PARSER_VERSION = '2.0', HEADER_ROW = TRUE, DATAFILETYPE = 'widechar', CODEPAGE = 'ACP', ROWSET_OPTIONS = '{"READ_OPTIONS":["ALLOW_INCONSISTENT_READS"]}') WITH ([region] VARCHAR (100)) AS a;
