CREATE TABLE table1 (
    a INT UNIQUE WITH (OPTIMIZE_FOR_SEQUENTIAL_KEY = ON),
    b INT UNIQUE WITH (OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
);

CREATE TABLE table1 (
    a INT,
    b INT,
    CONSTRAINT uq1 UNIQUE NONCLUSTERED (a) WITH (OPTIMIZE_FOR_SEQUENTIAL_KEY = ON),
    CONSTRAINT uq2 UNIQUE NONCLUSTERED (b) WITH (OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
);

ALTER TABLE table1
    ADD a INT CONSTRAINT uq1 UNIQUE WITH (OPTIMIZE_FOR_SEQUENTIAL_KEY = ON);

ALTER TABLE table1
    ADD a INT CONSTRAINT uq1 UNIQUE WITH (OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF);

ALTER TABLE table1
    ADD CONSTRAINT uq1 UNIQUE (a) WITH (OPTIMIZE_FOR_SEQUENTIAL_KEY = ON);

ALTER TABLE table1
    ADD CONSTRAINT uq1 UNIQUE (a) WITH (OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF);

